---
title: "ProcessingAndAnalysisScript_JAN2024"
author: "Dean Cisler"
date: "`r Sys.Date()`"
output:
  word_document: 
    toc: true
  html_document: default
  pdf_document: default
---

 

```{r}
#Libraries
library(readr)
library(readxl)
library(dplyr)
library(tidyr)
library(rstatix) #need to update to the latest version of r
library(psycho)
library(ggplot2)
library(hrbrthemes)
library(PerformanceAnalytics)
library(tools)
library(stringr)
library(factoextra)
library(digest)

#Creating the raw dataset

#Get the list of filenames and their paths
datalist = list()
file_names_listed_EXP1EnjoyRaw <- list.files(path = "C:/Users/Cisler/Desktop/Data/For Analysis/Exp1Enjoy/Raw", full.names = FALSE,
                                             pattern = "*.iqdat")

file_names_listed_EXP1NotEnjoyRaw <- list.files(path = "C:/Users/Cisler/Desktop/Data/For Analysis/Exp1NotEnjoy/Raw", full.names = FALSE,
                                             pattern = "*.iqdat")

file_names_listed_EXP2EnjoyRaw <- list.files(path = "C:/Users/Cisler/Desktop/Data/For Analysis/Exp2Enjoy/Raw", full.names = FALSE,
                                             pattern = "*.iqdat")

file_names_listed_EXP2NotEnjoyRaw <- list.files(path = "C:/Users/Cisler/Desktop/Data/For Analysis/Exp2NotEnjoy/Raw", full.names = FALSE,
                                             pattern = "*.iqdat")

file_names_listed_EXP3EnjoyRaw <- list.files(path = "C:/Users/Cisler/Desktop/Data/For Analysis/Exp3Enjoy/SART/Raw", full.names = FALSE,
                                             pattern = "*.iqdat")

file_names_listed_EXP3NotEnjoyRaw <- list.files(path = "C:/Users/Cisler/Desktop/Data/For Analysis/Exp3NotEnjoy/SART/Raw", full.names = FALSE,
                                             pattern = "*.iqdat")

file_names_listed_EXP3TSEnjoyRaw <- list.files(path = "C:/Users/Cisler/Desktop/Data/For Analysis/Exp3Enjoy/TS/Raw", full.names = FALSE,
                                             pattern = "*.iqdat")

file_names_listed_EXP3TSNotEnjoyRaw <- list.files(path = "C:/Users/Cisler/Desktop/Data/For Analysis/Exp3NotEnjoy/TS/Raw", full.names = FALSE,
                                             pattern = "*.iqdat")

file_names <- c(file_names_listed_EXP1EnjoyRaw, file_names_listed_EXP1NotEnjoyRaw, file_names_listed_EXP2EnjoyRaw, file_names_listed_EXP2NotEnjoyRaw, file_names_listed_EXP3EnjoyRaw, file_names_listed_EXP3NotEnjoyRaw, file_names_listed_EXP3TSEnjoyRaw, file_names_listed_EXP3TSNotEnjoyRaw)

#Load Each List Into Its Own Dataframe the Merge Them All Together
path1 = "C:/Users/Cisler/Desktop/Data/For Analysis/Exp1Enjoy/Raw/"
path2 = "C:/Users/Cisler/Desktop/Data/For Analysis/Exp1NotEnjoy/Raw/"
path3 = "C:/Users/Cisler/Desktop/Data/For Analysis/Exp2Enjoy/Raw/"
path4 = "C:/Users/Cisler/Desktop/Data/For Analysis/Exp2NotEnjoy/Raw/"
path5 = "C:/Users/Cisler/Desktop/Data/For Analysis/Exp3Enjoy/SART/Raw/"
path6 = "C:/Users/Cisler/Desktop/Data/For Analysis/Exp3NotEnjoy/SART/Raw/"
path7 = "C:/Users/Cisler/Desktop/Data/For Analysis/Exp3Enjoy/TS/Raw/"
path8 = "C:/Users/Cisler/Desktop/Data/For Analysis/Exp3NotEnjoy/TS/Raw/"

folder_paths <- c(path1, path2, path3, path4, path5, path6, path7, path8)

# Create an empty list to store dataframes
dataframes_list <- list()

# Loop through the folder paths and load each file into a dataframe
tryCatch({
for (folder_path in folder_paths) {
  
  files_in_folder <- list.files(path = folder_path, full.names = TRUE)

  # Iterate through each file in the folder
    for (file_path in files_in_folder) {
      # Read the file using the full path with read_csv
      data <- read.table(file_path,
                     sep='\t', header=TRUE, stringsAsFactors = FALSE)
      
      # Extract the file name without extension
      file_name <- tools::file_path_sans_ext(basename(file_path))
      
      # Update the dataframe name using the file name
      dataframe_name <- paste0("df_", file_name)
  
  # Assign the dataframe to the list
  dataframes_list[[dataframe_name]] <- data
  }
}
}, error = function(e) {
  cat("An error occurred:", conditionMessage(e), "\n")
})

RawDataSet <- bind_rows(dataframes_list, .id = "source")

#Again but with the survey data
#Load Each List Into Its Own Dataframe the Merge Them All Together
path1 = "C:/Users/Cisler/Desktop/Data/For Analysis/Exp1Enjoy/Survey/"
path2 = "C:/Users/Cisler/Desktop/Data/For Analysis/Exp1NotEnjoy/Survey/"
path3 = "C:/Users/Cisler/Desktop/Data/For Analysis/Exp2Enjoy/Survey/"
path4 = "C:/Users/Cisler/Desktop/Data/For Analysis/Exp2NotEnjoy/Survey/"
path5 = "C:/Users/Cisler/Desktop/Data/For Analysis/Exp3Enjoy/SART/Survey/"
path6 = "C:/Users/Cisler/Desktop/Data/For Analysis/Exp3NotEnjoy/SART/Survey/"
path7 = "C:/Users/Cisler/Desktop/Data/For Analysis/Exp3Enjoy/TS/Survey/"
path8 = "C:/Users/Cisler/Desktop/Data/For Analysis/Exp3NotEnjoy/TS/Survey/"

folder_paths_survey <- c(path1, path2, path3, path4, path5, path6, path7, path8)

# Create an empty list to store dataframes
dataframes_list_survey <- list()

# Loop through the folder paths and load each file into a dataframe
tryCatch({
for (folder_path in folder_paths_survey) {
  
  files_in_folder <- list.files(path = folder_paths_survey, full.names = TRUE)

  # Iterate through each file in the folder
    for (file_path in files_in_folder) {
      # Read the file using the full path with read_csv
      data <- read.table(file_path,
                     sep='\t', header=TRUE, stringsAsFactors = FALSE)
      
      # Extract the file name without extension
      file_name <- tools::file_path_sans_ext(basename(file_path))
      
      # Update the dataframe name using the file name
      dataframe_name <- paste0("df_", file_name)
  
  # Assign the dataframe to the list
  dataframes_list_survey[[dataframe_name]] <- data
  }
}
}, error = function(e) {
  cat("An error occurred:", conditionMessage(e), "\n")
})

SurveyDataSet <- bind_rows(dataframes_list_survey, .id = "source")

CompleteDataSet <- left_join(RawDataSet, SurveyDataSet, by = 'subject')

###Add in Exp Number and Condition
list1 <- list.files(path = "C:/Users/Cisler/Desktop/Data/For Analysis/Exp1Enjoy/Raw", full.names = FALSE,
                                             pattern = "*.iqdat")

list2 <- list.files(path = "C:/Users/Cisler/Desktop/Data/For Analysis/Exp1NotEnjoy/Raw", full.names = FALSE,
                                             pattern = "*.iqdat")

list3 <- list.files(path = "C:/Users/Cisler/Desktop/Data/For Analysis/Exp2Enjoy/Raw", full.names = FALSE,
                                             pattern = "*.iqdat")

list4 <- list.files(path = "C:/Users/Cisler/Desktop/Data/For Analysis/Exp2NotEnjoy/Raw", full.names = FALSE,
                                             pattern = "*.iqdat")

list5 <- list.files(path = "C:/Users/Cisler/Desktop/Data/For Analysis/Exp3Enjoy/SART/Raw", full.names = FALSE,
                                             pattern = "*.iqdat")

list6 <- list.files(path = "C:/Users/Cisler/Desktop/Data/For Analysis/Exp3NotEnjoy/SART/Raw", full.names = FALSE,
                                             pattern = "*.iqdat")

list7 <- list.files(path = "C:/Users/Cisler/Desktop/Data/For Analysis/Exp3Enjoy/TS/Raw", full.names = FALSE,
                                             pattern = "*.iqdat")

list8 <- list.files(path = "C:/Users/Cisler/Desktop/Data/For Analysis/Exp3NotEnjoy/TS/Raw", full.names = FALSE,
                                             pattern = "*.iqdat")

list1 <- sub("\\.iqdat$", "", list1)
list2 <- sub("\\.iqdat$", "", list2)
list3 <- sub("\\.iqdat$", "", list3)
list4 <- sub("\\.iqdat$", "", list4)
list5 <- sub("\\.iqdat$", "", list5)
list6 <- sub("\\.iqdat$", "", list6)
list7 <- sub("\\.iqdat$", "", list7)
list8 <- sub("\\.iqdat$", "", list8)

CompleteDataSet$source.x <- gsub("^df_", "", CompleteDataSet$source.x)
df <- CompleteDataSet

# Create conditions for each list
condition1 <- df$source.x %in% list1
condition2 <- df$source.x %in% list2
condition3 <- df$source.x %in% list3
condition4 <- df$source.x %in% list4
condition5 <- df$source.x %in% list5
condition6 <- df$source.x %in% list6
condition7 <- df$source.x %in% list7
condition8 <- df$source.x %in% list8

# Repeat for list3, list4, ..., list8

# Apply conditions iteratively
df <- df %>%
  mutate(
    new_exp_column = case_when(
      condition1 ~ "EXP1",
      condition2 ~ "EXP1",
      condition3 ~ "EXP2",
      condition4 ~ "EXP2",
      condition5 ~ "EXP3-SART",
      condition6 ~ "EXP3-SART",
      condition7 ~ "EXP3-TS",
      condition8 ~ "EXP3-TS",
      # Add more conditions for other lists if needed
      TRUE ~ NA_character_
    ),
    new_cond_column = case_when(
      condition1 ~ "Enjoy",
      condition2 ~ "NotEnjoy",
      condition3 ~ "Enjoy",
      condition4 ~ "NotEnjoy",
      condition5 ~ "Enjoy",
      condition6 ~ "NotEnjoy",
      condition7 ~ "Enjoy",
      condition8 ~ "NotEnjoy",
      # Add more conditions for other lists if needed
      TRUE ~ NA_character_
    )
  )

# Remove temporary conditions
rm(condition1, condition2, condition3, condition4, condition5, condition6, condition7, condition8)

df$mturk_sona <- ifelse(grepl("mturk", df$source.x), "MT", "SS")


```

```{r Data Integrity}
#Files with incomplete data were deleted.  These are files where they forced closed the program without exiting using the ctrl+Q command.  This was done through visual inspection and were identified by the low number of trials and lack of post survey responses.

#Do they have post survey responses?  If no remove them as it means they quit the task
SubRaw <- unique(RawDataSet$subject)
SubSurvey <- unique(SurveyDataSet$subject)

MissingPost <- SubRaw[!SubRaw %in% SubSurvey]

#Remove people who didn't try on the tasks or who screened themselves out.
CleanDataset <- df[!df$subject %in% MissingPost, ]

unique(CleanDataset$subject)

#SART Task Filters
CleanDatasetSART <- CleanDataset %>% filter(grepl("sart", source.x))
length(unique(CleanDatasetSART$subject))

CleanDatasetSART %>% group_by(new_exp_column, new_cond_column) %>% summarize(num_people = n_distinct(subject))

#DQ'd if responsed to less than 50% of trials
zero_count_df <- CleanDatasetSART %>%
  group_by(subject) %>%
  summarize(zero_count = sum(response == 0, na.rm = TRUE))

# Calculate the total trial count for each subject
total_count_df <- CleanDatasetSART %>%
  group_by(subject) %>%
  summarize(total_count = n())

# Merge the two data frames and calculate the percentage of zero counts out of the total count
PercentResp_result <- merge(zero_count_df, total_count_df, by = "subject", all = TRUE) %>%
  mutate(zero_count = ifelse(is.na(zero_count), 0, zero_count),  # Replace NA with 0
         zero_percentage = (zero_count / total_count) * 100)  # Calculate the percentage

#Over 50% trials missing responses
MajorityMissing <- PercentResp_result %>% filter(zero_percentage > 50)

#List of those to exclude
remove_for_missingness <- MajorityMissing$subject
CleanDatasetSART <- CleanDatasetSART[!CleanDatasetSART$subject %in% remove_for_missingness, ]

CleanDatasetSART %>% group_by(new_exp_column, new_cond_column) %>% summarize(num_people = n_distinct(subject))

#DQ'd for speedy responses < 300ms on the majority of trials
#SARTcheck <- SART_RTcheck %>% filter(new_exp_column == 'EXP1')
SART_RTcheck <- CleanDatasetSART %>% filter(blockcode == 'SART')
SART_RTcheck <- SART_RTcheck %>% filter(trialtype != 'probe')
SART_RTcheck <- SART_RTcheck %>% filter(trialtype != 'probe2')

SART_RTmean <- aggregate(latency ~ subject + new_exp_column + new_cond_column, SART_RTcheck, mean)

SART_SpeedyResponses <- SART_RTmean %>% filter(latency < 300)
RemoveSpeedyResp <- SART_SpeedyResponses$subject

CleanDatasetSART <- CleanDatasetSART[!CleanDatasetSART$subject %in% RemoveSpeedyResp, ]
CleanDatasetSART %>% group_by(new_exp_column, new_cond_column) %>% summarize(num_people = n_distinct(subject))

TSdataset <- CleanDataset %>% filter(grepl("numberlettertask", source.x))

  
  
CleanDatasetSARTList <- unique(CleanDatasetSART$subject)
df <- df[df$subject %in% CleanDatasetSARTList, ]
df <- rbind(df, TSdataset)
df %>% group_by(new_exp_column, new_cond_column) %>% summarize(num_people = n_distinct(subject))


#Additional Outliers Identified 
outliers_remove <- c('511196234', '864810148', '684125186', '538020870', '919874702', '508666212')
#511196234, 864810148, 684125186, 538020870

df <- df[!df$subject %in% outliers_remove, ]


#Task Switching Analysis
Experiment3TSclean <- df %>% filter(new_exp_column == "EXP3-TS")
Experiment3TSclean <- Experiment3TSclean %>% filter(blockcode == "combinedTask")

#There is an extra data cleaning step to account for here.  I need to eliminate the trials where button mashing occurred.
Experiment3TSclean <- Experiment3TSclean %>% filter(latency > 500)

#Provides a count of how many rows have a response higher than 500 ms
row_count_per_participant <- Experiment3TSclean %>%
  group_by(subject) %>%
  summarize(row_count = n())

#There are a total of 1200 trials in the main task.  If participants had a latency lower than 500 ms on 60% or more of trials, they were removed.
TSppl_remove <- row_count_per_participant %>% filter(row_count < 500)
TSid_remove <- TSppl_remove$subject

#If I exclude responses occurring 500 ms then two people fall outside the criteria for inclusion in the experiment (507417462 - Not Enjoy, 891302083 - Enjoy).
#If I exclude responses occurring 350 ms or below, there is one person that falls outside the criteria for inclusion (891302083 - Enjoy)
#I'm fine with excluding responses 500 ms and below.

df <- df[!df$subject %in% TSid_remove, ]
df %>% group_by(new_exp_column, new_cond_column) %>% summarize(num_people = n_distinct(subject))


```


```{r}




# Function to create MD5 checksum for a dataframe
create_checksum <- function(dataframe) {
  # Convert dataframe to a character string
  dataframe_str <- as.character(dataframe)
  
  # Create MD5 checksum using digest function
  md5_checksum <- digest(dataframe_str, algo = "md5", serialize = FALSE)
  
  return(md5_checksum)
}

# Create MD5 checksum for the example dataframe
#MindWanderingDissertation <- create_checksum(CompleteDataSet)

# Print the checksum
#print(MindWanderingDissertation)

#write.csv(df, "C:/Users/Cisler/Desktop/Data/For Analysis/CompleteDataSet.csv")





```




```{r}
#Analyses
library(RColorBrewer)
library(ISLR)
library(tidyverse)
library(Rfast)
library(MASS)
library(ggpubr)
library(vcd)
library(ggmosaic)
library(gridExtra)
library(lme4)
library(lmerTest)
source('https://github.com/pablobernabeu/language-sensorimotor-simulation-PhD-thesis/raw/main/R_functions/frequentist_model_table.R')

#Separate Out EXP1 and EXP2 into different dataframes
EXP1df <- df %>% filter(grepl("^EXP1", new_exp_column, ignore.case = TRUE))

EXP1MWcatch <- df %>% filter(grepl("MWcatch", trialcode, ignore.case = TRUE))
EXP1MWcatch$response <- as.numeric(EXP1MWcatch$response)
EXP1MWcatchaverages <- aggregate(response ~ subject, EXP1MWcatch, mean)
EXP1MWcatchaverages <- EXP1MWcatchaverages %>%
  rename(MWcatch_response = response)

EXP1MWonTask <- df %>% filter(grepl("MWonTask", trialcode, ignore.case = TRUE))
EXP1MWonTask$response <- as.numeric(EXP1MWonTask$response)
EXP1MWonTaskaverages <- aggregate(response ~ subject, EXP1MWonTask, mean)
EXP1MWonTaskaverages <- EXP1MWonTaskaverages %>%
  rename(MWonTask_response = response)

EXP1MWother <- df %>% filter(grepl("MWother", trialcode, ignore.case = TRUE))
EXP1MWother$response <- as.numeric(EXP1MWother$response)
EXP1MWotheraverages <- aggregate(response ~ subject, EXP1MWother, mean)
EXP1MWotheraverages <- EXP1MWotheraverages %>%
  rename(MWother_response = response)

EXP1MWcatchTrialsAverages <- merge(merge(EXP1MWcatchaverages, EXP1MWonTaskaverages, by = "subject"), EXP1MWotheraverages, by = "subject")

EXP2df <- df %>% filter(grepl("^EXP2", new_exp_column, ignore.case = TRUE))

#Filters code for probe responses only
EXP1df <- EXP1df %>% filter(grepl('probe', trialcode))

#Filter to exclude probe2 responses
EXP1df <- EXP1df %>% filter(!grepl('probe2', trialcode))
#ProbeRespons$filt <- ProbeRespons$filt %>% replace_na('filter1')

EXP1probe <- EXP1df %>% dplyr::select(subject, new_exp_column, new_cond_column, response, paid_response, mturk_sona)
EXP1probe <- EXP1probe %>% rename(probe_response = response)

EXP2probe <- EXP2df %>% dplyr::select(subject, new_exp_column, new_cond_column, probe_response, paid_response, mturk_sona)
EXP2probe <- EXP2probe[!duplicated(EXP2probe$subject), ]

ProbeRespons <- rbind(EXP1probe, EXP2probe)


#
PersonProbeCount <- ProbeRespons %>% group_by(subject, new_exp_column, new_cond_column) %>% count(probe_response)


exp1tab <- ProbeRespons %>% filter(new_exp_column == 'EXP1')
exp2tab <- ProbeRespons %>% filter(new_exp_column == 'EXP2')
con3 <- xtabs( ~ new_cond_column+probe_response, data = exp1tab)
con3

Exp1prop <- prop.table(con3, margin = 1)
Exp1prop
mosaicplot(Exp1prop)

title <- "Proportion of Responses to the\nMind Wandering Probes\nAdministered During the Task\nby Enjoyment Condition"

intProbe <- ggplot(data = EXP1probe)+
  geom_mosaic(aes(x = product(probe_response, new_cond_column), fill=new_cond_column), na.rm=TRUE) +
  geom_mosaic_text(aes(x = product(probe_response, new_cond_column), 
                       label = after_stat(.wt)), as.label=TRUE) +
  labs(
    x = "Enjoyment Condition",
    y = "Responses to Mind Wandering Probe") +
  ggtitle(title
  ) +
  guides(fill = "none")
intProbe

con4 <- xtabs( ~ new_cond_column+probe_response, data = exp2tab)
con4
Exp2prop <- prop.table(con4, margin = 1)
Exp2prop
mosaicplot(Exp2prop)

title <- "Proportion of Responses to the\nMind Wandering Probes\nAdministered Post Task\nby Enjoyment Condition"

postProbe <- ggplot(data = EXP2probe)+
geom_mosaic(aes(x = product(probe_response, new_cond_column), fill=new_cond_column), na.rm=TRUE) +
  labs(
    x = "Enjoyment Condition",
    y = "Responses to Mind Wandering Probe") +
    ggtitle(title) +
  guides(fill = "none")
postProbe

bothPlots <- grid.arrange(intProbe, postProbe, ncol = 2)
ggsave("arranged_plots.png", bothPlots, width = 12, height = 6, units = "in", dpi = 300)

grid.arrange(intProbe, postProbe, ncol = 2)

###########################################################################################
#End Creating Mosaic Plots
###########################################################################################

###########################################################################################
#Creating Tables and Plots on re-engagement with the task; Analysis of SART Data
###########################################################################################
# Create a function to process each subject
process_subject <- function(subject_data) {
  # Count the number of "Yes" and "No" responses
  yes_count <- sum(subject_data$probe_response == "Yes")
  no_count <- sum(subject_data$probe_response == "No")
  
  # Compare counts and assign a value based on the majority response
  if (yes_count > no_count) {
    result <- "Yes"
  } else if (yes_count < no_count) {
    result <- "No"
  } else {
    result <- "Tie"  # Handle tie situations if needed
  }
  
  return(result)
}

# Iterate through subjects and process each one
results <- sapply(split(ProbeRespons, ProbeRespons$subject), process_subject)

# Display the results
MWresult_dataExp1Exp2 <- data.frame(subject = names(results), MWer = results)
print(MWresult_dataExp1Exp2)
MWresult_dataExp1Exp2$subject <- as.integer(MWresult_dataExp1Exp2$subject)



MWassign <- left_join(ProbeRespons, MWresult_dataExp1Exp2, by = 'subject')

Exp1EnjoyAnalysis <- MWassign %>% filter(new_exp_column == 'EXP1')
Exp1EnjoyAnalysis <- Exp1EnjoyAnalysis %>% filter(new_cond_column == 'Enjoy')
#Exp1EnjoyAnalysis <- Exp1EnjoyAnalysis %>% filter(filt == 'filter1')
Exp1EnjoyAnalysis <- Exp1EnjoyAnalysis %>% distinct(subject, .keep_all = TRUE)

Exp1NotEnjoyAnalysis <- MWassign %>% filter(new_exp_column == 'EXP1')
Exp1NotEnjoyAnalysis <- Exp1NotEnjoyAnalysis %>% filter(new_cond_column == 'NotEnjoy')
#Exp1NotEnjoyAnalysis <- Exp1NotEnjoyAnalysis %>% filter(filt == 'filter1')
Exp1NotEnjoyAnalysis <- Exp1NotEnjoyAnalysis %>% distinct(subject, .keep_all = TRUE)

Exp2EnjoyAnalysis <- MWassign %>% filter(new_exp_column == 'EXP2')
Exp2EnjoyAnalysis <- Exp2EnjoyAnalysis %>% filter(new_cond_column == 'Enjoy')
#Exp2EnjoyAnalysis <- Exp2EnjoyAnalysis %>% filter(filt == 'filter1')
Exp2EnjoyAnalysis <- Exp2EnjoyAnalysis %>% distinct(subject, .keep_all = TRUE)

Exp2NotEnjoyAnalysis <- MWassign %>% filter(new_exp_column == 'EXP2')
Exp2NotEnjoyAnalysis <- Exp2NotEnjoyAnalysis %>% filter(new_cond_column == 'NotEnjoy')
#Exp2NotEnjoyAnalysis <- Exp2NotEnjoyAnalysis %>% filter(filt == 'filter1')
Exp2NotEnjoyAnalysis <- Exp2NotEnjoyAnalysis %>% distinct(subject, .keep_all = TRUE)

exp1exp2Analysis <- rbind(Exp1EnjoyAnalysis, Exp2EnjoyAnalysis, Exp1NotEnjoyAnalysis, Exp2NotEnjoyAnalysis)

exp1exp2Analysis2 <- exp1exp2Analysis
exp1exp2Analysis2$new_exp_column <- as.factor(exp1exp2Analysis2$new_exp_column)
exp1exp2Analysis2$new_cond_column <- as.factor(exp1exp2Analysis2$new_cond_column)
exp1exp2Analysis2$MWer <- as.factor(exp1exp2Analysis2$MWer)

# exp1Analysis <- exp1exp2Analysis2
# exp1Analysis <- exp1Analysis %>% filter(new_exp_colum == 'exp1')
# 
# exp2Analysis <- exp1exp2Analysis2
# exp2Analysis <- exp2Analysis %>% filter(new_exp_colum == 'exp2')



# write.csv(exp1exp2Analysis2, "C:/Users/Cisler/Desktop/Data/For Analysis/ProbeAnalysisForRQs1and2.csv")
# write.csv(df, "C:/Users/Cisler/Desktop/Data/For Analysis/CompleteDatasetWithTransformationsAndModifications_17JAN2024.csv")

MWerModel <- glm(formula = MWer ~ mturk_sona + new_exp_column + new_cond_column + new_exp_column:new_cond_column + mturk_sona:new_cond_column, family = binomial(link = "logit"), 
    data = exp1exp2Analysis2)
summary(MWerModel)
exp(MWerModel$coefficients)
exp(Confint(MWerModel))

#cor.test(exp1exp2Analysis2$MWer, exp1exp2Analysis2$new_exp_column)

contingency_table <- table(exp1exp2Analysis2$MWer, exp1exp2Analysis2$new_exp_column)
exp1exp2Analysis3 <- exp1exp2Analysis2[exp1exp2Analysis2$MWer != 'Tie', ]
exp1exp2Analysis3 <- exp1exp2Analysis2[!(exp1exp2Analysis2$MWer == 'Tie' | exp1exp2Analysis2$new_exp_column == 'Tie'), ]
exp1exp2Analysis3 <- exp1exp2Analysis2 %>% filter(MWer != "Tie")
contingency_table <- table(exp1exp2Analysis3$MWer, exp1exp2Analysis3$new_exp_column)
interaction_table <- xtabs(~ MWer + new_exp_column + mturk_sona, data = exp1exp2Analysis2)


```
```{r}
####Analysis of SART Performance
SARTexp1 <- df %>% filter(new_exp_column == "EXP1")

SARTexp1 <- SARTexp1 %>% filter(blockcode == "SART")
SARTexp1 <- SARTexp1 %>% filter(trialcode != "probe")
SARTexp1 <- SARTexp1 %>% filter(trialcode != "probe2")
SARTexp1 <- SARTexp1 %>% filter(trialcode != "MWcatch")
SARTexp1 <- SARTexp1 %>% filter(trialcode != "MWonTask")
SARTexp1 <- SARTexp1 %>% filter(trialcode != "MWother")

SARTexp2 <- df %>% filter(new_exp_column == "EXP2")
SARTexp2 <- SARTexp2 %>% filter(blockcode == "SART")

SARTexp1exp2 <- rbind(SARTexp1, SARTexp2)
SARTexp1exp2 <- left_join(SARTexp1exp2, MWresult_dataExp1Exp2, by = "subject")

SARTexp1exp2 <- SARTexp1exp2 %>% filter(MWer != "Tie")

#NASA-TLX Transformations
SARTexp1exp2 <- SARTexp1exp2 %>%
  mutate(mentaldemand_response_coded = (mentaldemand_response - 1) * 5)


SARTexp1exp2 <- SARTexp1exp2 %>%
  mutate(physicaldemand_response_coded = (physicaldemand_response - 1) * 5)


SARTexp1exp2 <- SARTexp1exp2 %>%
  mutate(temporaldemand_response_coded = (temporaldemand_response - 1) * 5)


SARTexp1exp2 <- SARTexp1exp2 %>%
  mutate(performance_response_coded = (performance_response - 1) * 5)


SARTexp1exp2 <- SARTexp1exp2 %>%
  mutate(effort_response_coded = (effort_response - 1) * 5)

SARTexp1exp2 <- SARTexp1exp2 %>%
  mutate(frustration_response_coded = (frustration_response - 1) * 5)


SARTexp1exp2$hit <- ifelse(SARTexp1exp2$trialtype == "NoGo" & SARTexp1exp2$correct == 1, 1, 0)
SARTexp1exp2$miss <- ifelse(SARTexp1exp2$trialtype == "NoGo" & SARTexp1exp2$correct == 0, 1, 0)
SARTexp1exp2$CR <- ifelse(SARTexp1exp2$trialtype == "Go" & SARTexp1exp2$correct == 1, 1, 0)
SARTexp1exp2$FA <- ifelse(SARTexp1exp2$trialtype == "Go" & SARTexp1exp2$correct == 0, 1, 0)


SARTrtFilt <- SARTexp1exp2 %>% filter(correct == 1)
SARTrtFilt <- SARTexp1exp2 %>% filter(trialtype == "Go")
SARTfaFilt <- SARTexp1exp2 %>% filter(trialtype == "Go")

SARTaccFilt <- SARTexp1exp2 %>% filter(trialtype == "NoGo")
SARTmissFilt <- SARTexp1exp2 %>% filter(trialtype == "NoGo")

FAmean <- aggregate(FA ~ subject + new_exp_column + new_cond_column, SARTfaFilt, mean)
Hitmean <- aggregate(correct ~ subject + new_exp_column + new_cond_column, SARTaccFilt, mean)
Missmean <- aggregate(CR ~ subject + new_exp_column + new_cond_column, SARTrtFilt, mean)
RTmean <- aggregate(latency ~ subject + new_exp_column + new_cond_column, SARTrtFilt, mean)

QualCheck <- left_join(Hitmean, FAmean, by = "subject") %>%
  left_join(Missmean, by = "subject") %>%
  left_join(RTmean, by = "subject")
QualCheckExp1 <- QualCheck %>% filter(new_exp_column.x == "EXP1")
#Subject 566606496 is an outlier.  It appears they just kept hitting the space bar.  This person should have been excluded.  For some reason, they made it through my exclusion checks
QualCheck2 <- SARTexp1exp2 %>% filter(subject == "566606496")

QualCheckExp2 <- QualCheck %>% filter(new_exp_column.x == "EXP2")
QualCheck2_2 <- SARTexp1exp2 %>% filter(subject == "197955474")
#Nothing is overtly odd about their data.  My only concern is that the datafile was recorded at 2:30 am.  They could be fatigued.

###Analysis of RT for SART
# RTlm <- lm(latency~new_exp_column*new_cond_column, data = SARTrtFilt)
# summary(RTlm)

RTlm <- lmer(latency~mturk_sona*new_exp_column*new_cond_column + (1|subject), data = SARTrtFilt)
summary(RTlm)


RTlmConfInt <- confint(RTlm)
RTLMERresults <- summary(RTlm)
frequentist_model_table(RTLMERresults, RTlmConfInt,
 # Replace colons in the names of interactions with times symbols
  interaction_symbol_x = TRUE, 
  
  #Rename Title, for No title replace text with NULL
  caption = "Latency by Probe Placement and Enjoyment Condition")

RTlm <- lmer(latency~mturk_sona+new_exp_column+new_cond_column + (1|subject), data = SARTrtFilt)
RTlmConfInt <- confint(RTlm)
RTLMERresults <- summary(RTlm)
frequentist_model_table(RTLMERresults, RTlmConfInt,
 # Replace colons in the names of interactions with times symbols
  interaction_symbol_x = TRUE, 
  
  #Rename Title, for No title replace text with NULL
  caption = "Latency by Probe Placement and Enjoyment Condition")

RTbyGroup <- ggplot(SARTrtFilt, aes(x = new_cond_column, y = latency, fill = new_exp_column)) +
    stat_summary(
    fun = "mean", 
    geom = "bar", 
    position = position_dodge(width = 0.9),
    aes(label = round(..y.., digits = 2)),
    vjust = -0.5
  ) +
  geom_text(
    stat = "summary", 
    fun = "mean", 
    aes(label = round(..y.., digits = 2)),
    position = position_dodge(width = 0.9),
    vjust = -0.5
  ) +
  labs(
   x = "Enjoyment Condition",
    y = "Average Reaction Time",
    title = "Average Reaction Time Between Enjoyment and Probe Conditions"
  ) +
  theme_minimal()
RTbyGroup

participant_avg_latencyExp1 <- SARTrtFilt %>%
  group_by(subject, mturk_sona) %>%
  summarize(avg_latency = mean(latency),
            sd_latency = sd(latency))

# View the new dataframe
print(participant_avg_latencyExp1)

RTbyMWExp1 <- ggplot(participant_avg_latencyExp1, aes(x = mturk_sona, y = avg_latency, fill = mturk_sona)) + 
  geom_violin(trim = FALSE) +
  labs(title = "Average Reaction Time of Go Trials Between MTurk and SONA System Participants", 
       x = "Participant Pool", 
       y = "Average Reaction Time of Go Trials",
       fill = "Switch") +
  scale_x_discrete(labels = c("MT" = "MTurk", "SS" = "SONA Systems")) +
  scale_fill_manual(values = c("MT" = "blue", "SS" = "red"),
                    labels = c("MT" = "MTurk", "SS" = "SONA Systems")) +
  guides(fill = FALSE)  # Explicitly remove the legend

RTbyMWExp1 + stat_summary(fun.data="mean_sdl", mult=1,
                                  geom="crossbar", width=0.2, stackdir='center',
                                  position=position_dodge(.9))
RTbyMWExp1 + stat_summary(fun.data=mean_sdl, mult=1,
                                  geom="pointrange", color="black", stackdir='center',
                                  position=position_dodge(.9))


RTbyConditionsInt <- SARTrtFilt %>%
  group_by(new_exp_column, new_cond_column) %>%
  summarize(mean_value = mean(paid_response))

RTbyConditionParticipantInt <- SARTrtFilt %>%
  group_by(new_exp_column, mturk_sona) %>%
  summarize(mean_value = mean(paid_response))


#####Analysis of ACC for SART NoGo Trials
# ACClm <- lm(correct ~ new_exp_column*new_cond_column, data = SARTaccFilt)
# summary(ACClm)

ACClm <- lmer(correct ~ mturk_sona*new_exp_column*new_cond_column + (1|subject), data = SARTaccFilt)
ACClmConfInt <- confint(ACClm)
ACCLMERresults <- summary(ACClm)
frequentist_model_table(ACCLMERresults, ACClmConfInt,
 # Replace colons in the names of interactions with times symbols
  interaction_symbol_x = TRUE, 
  
  #Rename Title, for No title replace text with NULL
  caption = "Accuracy to No Go Trials by Probe Placement and Enjoyment Condition")

ACClm <- lmer(correct ~ mturk_sona+new_exp_column+new_cond_column + (1|subject), data = SARTaccFilt)
ACClmConfInt <- confint(ACClm)
ACCLMERresults <- summary(ACClm)
frequentist_model_table(ACCLMERresults, ACClmConfInt,
 # Replace colons in the names of interactions with times symbols
  interaction_symbol_x = TRUE, 
  
  #Rename Title, for No title replace text with NULL
  caption = "Accuracy to No Go Trials by Probe Placement and Enjoyment Condition")


ACCbyGroup <- ggplot(SARTaccFilt, aes(x = new_cond_column, y = correct, fill = new_exp_column)) +
  stat_summary(
    fun = "mean", 
    geom = "bar", 
    position = position_dodge(width = 0.9),
    aes(label = round(..y.., digits = 2)),
    vjust = -0.5
  ) +
  geom_text(
    stat = "summary", 
    fun = "mean", 
    aes(label = round(..y.., digits = 2)),
    position = position_dodge(width = 0.9),
    vjust = -0.5
  ) +
  labs(
   x = "Enjoyment Condition",
    y = "Average Reaction Time",
    title = "Average Accuracy of No Go Trials Between Enjoyment and Probe Conditions"
  ) +
  theme_minimal()
ACCbyGroup

participant_avg_accExp1 <- SARTaccFilt %>%
  group_by(subject, mturk_sona) %>%
  summarize(avg_correct = mean(correct),
            sd_correct = sd(correct))

# View the new dataframe
print(participant_avg_accExp1)

ACCbyMWExp1 <- ggplot(participant_avg_accExp1, aes(x = mturk_sona, y = avg_correct, fill = mturk_sona)) + 
  geom_violin(trim = FALSE) +
  labs(title = "Average Accuracy of No Go Trials Between MTurk and SONA System Participants", 
       x = "Participant Pool", 
       y = "Average Accuracy of No Go Trials",
       fill = "Switch") +
  scale_x_discrete(labels = c("MT" = "MTurk", "SS" = "SONA Systems")) +
  scale_fill_manual(values = c("MT" = "blue", "SS" = "red"),
                    labels = c("MT" = "MTurk", "SS" = "SONA Systems")) +
  guides(fill = FALSE)  # Explicitly remove the legend

ACCbyMWExp1 + stat_summary(fun.data="mean_sdl", mult=1,
                                  geom="crossbar", width=0.2, stackdir='center',
                                  position=position_dodge(.9))
ACCbyMWExp1 + stat_summary(fun.data=mean_sdl, mult=1,
                                  geom="pointrange", color="black", stackdir='center',
                                  position=position_dodge(.9))



SARTfaFilt <- SARTrtFilt
SARTmissFILT <- SARTaccFilt

#Remember*** I am interpreting the target (No Go trials) as hits.  So withholding a response on a Go trial would be an FA
# FAlm <- lm(FA ~ new_exp_column*new_cond_column, data = SARTfaFilt)
# summary(FAlm)

FAlm <- lmer(FA ~ mturk_sona*new_exp_column*new_cond_column + (1|subject), data = SARTfaFilt)
FAlmConfInt <- confint(FAlm)
FALMERresults <- summary(FAlm)
frequentist_model_table(FALMERresults, FAlmConfInt,
 # Replace colons in the names of interactions with times symbols
  interaction_symbol_x = TRUE, 
  
  #Rename Title, for No title replace text with NULL
  caption = "False Alarms by Probe Placement and Enjoyment Condition")

FAlm <- lmer(FA ~ mturk_sona+new_exp_column+new_cond_column + (1|subject), data = SARTfaFilt)
FAlmConfInt <- confint(FAlm)
FALMERresults <- summary(FAlm)
frequentist_model_table(FALMERresults, FAlmConfInt,
 # Replace colons in the names of interactions with times symbols
  interaction_symbol_x = TRUE, 
  
  #Rename Title, for No title replace text with NULL
  caption = "False Alarms by Probe Placement and Enjoyment Condition")




FAbyGroup <- ggplot(SARTfaFilt, aes(x = new_cond_column, y = FA, fill = new_exp_column)) +
  stat_summary(
    fun = "mean", 
    geom = "bar", 
    position = position_dodge(width = 0.9),
    aes(label = round(..y.., digits = 2)),
    vjust = -0.5
  ) +
  geom_text(
    stat = "summary", 
    fun = "mean", 
    aes(label = round(..y.., digits = 3)),
    position = position_dodge(width = 0.9),
    vjust = -0.5
  ) +
  labs(
   x = "Enjoyment Condition",
    y = "Average False Alarms",
    title = "Average False Alarms of Go Trials Between Enjoyment and Probe Conditions"
  ) +
  theme_minimal()
FAbyGroup

FAbyConditionsInt <- SARTfaFilt %>%
  group_by(new_exp_column, new_cond_column) %>%
  summarize(mean_value = mean(FA))

FAbyConditionsInt

ggplot(SARTfaFilt, aes(x = FA, fill = new_cond_column)) +
  geom_density(alpha=0.2)


FAbySub <- SARTfaFilt %>% filter(new_exp_column == 'EXP1')

 
ggplot(FAbySub, aes(x = FA, fill = new_cond_column)) +
  geom_density(alpha=0.2)

FAbySub <- ggplot(SARTfaFilt, aes(x = subject, y = FA, fill = new_cond_column)) +
  stat_summary(
    fun = "mean", 
    geom = "bar", 
    position = position_dodge(width = 0.9),
    aes(label = round(..y.., digits = 2)),
    vjust = -0.5
  ) +
  geom_text(
    stat = "summary", 
    fun = "mean", 
    aes(label = round(..y.., digits = 3)),
    position = position_dodge(width = 0.9),
    vjust = -0.5
  ) +
  labs(
   x = "Enjoyment Condition",
    y = "Average False Alarms",
    title = "Average False Alarms of Go Trials Between Enjoyment and Probe Conditions"
  ) +
  theme_minimal()
FAbySub

participant_avg_faExp1 <- SARTfaFilt %>%
  group_by(subject, new_exp_column) %>%
  summarize(avg_FA = mean(FA),
            sd_FA = sd(FA))

# View the new dataframe
print(participant_avg_faExp1)

FAbyMWExp1 <- ggplot(participant_avg_faExp1, aes(x = new_exp_column, y = avg_FA, fill = new_exp_column)) + 
  geom_violin(trim = FALSE) +
  labs(title = "Average False Alarms of Go Trials By Probe Condition", 
       x = "Probe Condition", 
       y = "Average False Alarms of Go Trials",
       fill = "Switch") +
  scale_x_discrete(labels = c("EXP1" = "Interrupting Probe", "EXP2" = "Post Probe")) +
  scale_fill_manual(values = c("EXP1" = "blue", "EXP2" = "red"),
                    labels = c("EXP1" = "Interrupting Probe", "EXP2" = "Post Probe")) +
  guides(fill = FALSE)  # Explicitly remove the legend

FAbyMWExp1 + stat_summary(fun.data="mean_sdl", mult=1,
                                  geom="crossbar", width=0.2, stackdir='center',
                                  position=position_dodge(.9))
FAbyMWExp1 + stat_summary(fun.data=mean_sdl, mult=1,
                                  geom="pointrange", color="black", stackdir='center',
                                  position=position_dodge(.9))


participant_avg_faExp1_2 <- SARTfaFilt %>%
  group_by(subject, new_exp_column) %>%
  summarize(avg_FA = mean(FA),
            sd_FA = sd(FA))

# View the new dataframe
print(participant_avg_faExp1_2)

FAbyMWExp1_2 <- ggplot(participant_avg_faExp1_2, aes(x = new_exp_column, y = avg_FA, fill = new_exp_column)) + 
  geom_violin(trim = FALSE) +
  labs(title = "Average False Alarms of Go Trials Between MTurk and SONA System Participants", 
       x = "Participant Pool", 
       y = "Average False Alarms of Go Trials",
       fill = "Switch") +
  scale_x_discrete(labels = c("EXP1" = "Interrupting Probe", "EXP2" = "Post Probe")) +
  scale_fill_manual(values = c("EXP1" = "blue", "EXP2" = "red"),
                    labels = c("EXP1" = "Interrupting Probe", "EXP2" = "Post Probe"))

FAbyMWExp1_2 + stat_summary(fun.data="mean_sdl", mult=1,
                                  geom="crossbar", width=0.2, stackdir='center',
                                  position=position_dodge(.9))
FAbyMWExp1_2 + stat_summary(fun.data=mean_sdl, mult=1,
                                  geom="pointrange", color="black", stackdir='center',
                                  position=position_dodge(.9))


participant_avg_faExp1_3 <- SARTfaFilt %>%
  group_by(subject, new_exp_column, mturk_sona) %>%
  summarize(avg_FA = mean(FA),
            sd_FA = sd(FA))

# View the new dataframe
print(participant_avg_faExp1_3)

FAbyMWExp1_3 <- ggplot(participant_avg_faExp1_3, aes(x = new_exp_column, y = avg_FA, fill = mturk_sona)) + 
  geom_violin(trim = FALSE) +
  labs(title = "Average False Alarms of Go Trials Between MTurk and SONA System Participants", 
       x = "Participant Pool", 
       y = "Average False Alarms of Go Trials",
       fill = "Switch") +
  scale_x_discrete(labels = c("MT" = "MTurk", "SS" = "SONA Systems")) +
  scale_fill_manual(values = c("MT" = "blue", "SS" = "red"),
                    labels = c("MT" = "MTurk", "SS" = "SONA Systems"))

FAbyMWExp1_3 + stat_summary(fun.data="mean_sdl", mult=1,
                                  geom="crossbar", width=0.2, stackdir='center',
                                  position=position_dodge(.9))
FAbyMWExp1_3 + stat_summary(fun.data=mean_sdl, mult=1,
                                  geom="pointrange", color="black", stackdir='center',
                                  position=position_dodge(.9))


MISSbyGroup <- ggplot(SARTaccFilt, aes(x = new_cond_column, y = miss, fill = new_exp_column)) +
  stat_summary(
    fun = "mean", 
    geom = "bar", 
    position = position_dodge(width = 0.9),
    aes(label = round(..y.., digits = 2)),
    vjust = -0.5
  ) +
  geom_text(
    stat = "summary", 
    fun = "mean", 
    aes(label = round(..y.., digits = 3)),
    position = position_dodge(width = 0.9),
    vjust = -0.5
  ) +
  labs(
   x = "Enjoyment Condition",
    y = "Average Misses",
    title = "Average Misses of No Go Trials Between Enjoyment and Probe Conditions"
  ) +
  theme_minimal()
MISSbyGroup

MissbyConditionsInt <- SARTfaFilt %>%
  group_by(new_exp_column, new_cond_column) %>%
  summarize(mean_value = mean(miss))


CRbyGroup <- ggplot(SARTfaFilt, aes(x = new_cond_column, y = CR, fill = new_exp_column)) +
  stat_summary(
    fun = "mean", 
    geom = "bar", 
    position = position_dodge(width = 0.9),
    aes(label = round(..y.., digits = 2)),
    vjust = -0.5
  ) +
  geom_text(
    stat = "summary", 
    fun = "mean", 
    aes(label = round(..y.., digits = 3)),
    position = position_dodge(width = 0.9),
    vjust = -0.5
  ) +
  labs(
   x = "Enjoyment Condition",
    y = "Average Correct Rejections",
    title = "Average Correct Rejections of Go Trials Between Enjoyment and Probe Conditions"
  ) +
  theme_minimal()
CRbyGroup

CRbyConditionsInt <- SARTfaFilt %>%
  group_by(new_exp_column, new_cond_column) %>%
  summarize(mean_value = mean(CR))

#The misses and CR analyses are appearing as I expected.  The graphs and tables are just the inverse from the analyses of FAs and Hits.  I'm just going to 




```


```{r RQ Is Mind Wandering A Form of Task Switching}
#######################################################################################################
#Analyses of the RQ on Whether or not Mind Wandering and Task Switching share a cognitive mechanism
#######################################################################################################
#Congruency Condition
#1 = target symbol and distractor symbol share the same key
#2 = target symbol and distractor symbol require opposite keys

#Switch Condition
#0 = non-switch trial (even trials); (relevant for combined trials only)
#1 = switch trials (odd trials)


Experiment3TS <- df %>% filter(new_exp_column == "EXP3-TS")
Experiment3TS <- Experiment3TS %>% filter(blockcode == "combinedTask")


#Add in Mind Wandering Variable
TSMindWander <- Experiment3TS[!duplicated(Experiment3TS$subject), ]

# Create a function to process each subject
process_subject <- function(subject_data) {
  # Count the number of "Yes" and "No" responses
  yes_count <- sum(subject_data$probe_response == "Yes")
  no_count <- sum(subject_data$probe_response == "No")
  
  # Compare counts and assign a value based on the majority response
  if (yes_count > no_count) {
    result <- "Yes"
  } else if (yes_count < no_count) {
    result <- "No"
  } else {
    result <- "Tie"  # Handle tie situations if needed
  }
  
  return(result)
}

# Iterate through subjects and process each one
resultsTS <- sapply(split(TSMindWander, TSMindWander$subject), process_subject)

# Display the results
result_dataTS <- data.frame(subject = names(resultsTS), MWer = resultsTS)
print(result_dataTS)
result_dataTS %>% count(MWer)
result_dataTS$subject <- as.integer(result_dataTS$subject)


Experiment3TS <- left_join(Experiment3TS, result_dataTS, by = "subject")

Experiment3TS$congruence <- as.factor(Experiment3TS$congruence)
Experiment3TS$switch <- as.factor(Experiment3TS$switch)

##########################################################################################
#Propensity to Mind Wander
##########################################################################################
Experiment3TSprobeResp <- distinct(Experiment3TS, subject, .keep_all = TRUE)


title <- "Proportion of Responses to the Mind Wandering Probes For the Task Switching\nParadigm by Enjoyment Condition"

postProbeTS <- ggplot(data = Experiment3TSprobeResp)+
geom_mosaic(aes(x = product(probe_response, new_cond_column), fill=new_cond_column), na.rm=TRUE) +
  labs(
    x = "Enjoyment Condition",
    y = "Responses to Mind Wandering Probe") +
    ggtitle(title) +
  guides(fill = "none")
postProbeTS

Experiment3TSprobeResp %>% group_by(new_cond_column) %>% count(probe_response)

bothPlots <- grid.arrange(intProbe, postProbe, ncol = 2)
ggsave("arranged_plots.png", bothPlots, width = 12, height = 6, units = "in", dpi = 300)

grid.arrange(intProbe, postProbe, ncol = 2)

MWTS_groupings <- Experiment3TS[!duplicated(Experiment3TS$subject), ]
MWGroup_counts <- MWTS_groupings %>% 
  group_by(MWer, new_exp_column, new_cond_column) %>% 
  tally(name = "count_of_people")

TSlatency <- lmer(latency~new_cond_column*MWer*congruence*switch + (1|subject), data = Experiment3TS)
TSlatencyConfInt <- confint(TSlatency)
TSlatencyLMERresults <- summary(TSlatency)
frequentist_model_table(TSlatencyLMERresults, TSlatencyConfInt,
 # Replace colons in the names of interactions with times symbols
  interaction_symbol_x = TRUE, 
  
  #Rename Title, for No title replace text with NULL
  caption = "Latency by Enjoyment Condition, Mind Wanderer, Congruent and Switch Trials")

TSlatency <- lmer(latency~new_cond_column+MWer+congruence+switch + (1|subject), data = Experiment3TS)
TSlatencyConfInt <- confint(TSlatency)
TSlatencyLMERresults <- summary(TSlatency)
frequentist_model_table(TSlatencyLMERresults, TSlatencyConfInt,
 # Replace colons in the names of interactions with times symbols
  interaction_symbol_x = TRUE, 
  
  #Rename Title, for No title replace text with NULL
  caption = "Latency by Enjoyment Condition, Mind Wanderer, Congruent and Switch Trials")


TSlatency <- lmer(latency~MWer*congruence*switch + (1|subject), data = Experiment3TS)
TSlatencyConfInt <- confint(TSlatency)
TSlatencyLMERresults <- summary(TSlatency)
frequentist_model_table(TSlatencyLMERresults, TSlatencyConfInt,
 # Replace colons in the names of interactions with times symbols
  interaction_symbol_x = TRUE, 
  
  #Rename Title, for No title replace text with NULL
  caption = "Latency by Mind Wanderer, Congruent and Switch Trials")

TSlatency <- lmer(latency~MWer+congruence+switch + (1|subject), data = Experiment3TS)
TSlatencyConfInt <- confint(TSlatency)
TSlatencyLMERresults <- summary(TSlatency)
frequentist_model_table(TSlatencyLMERresults, TSlatencyConfInt,
 # Replace colons in the names of interactions with times symbols
  interaction_symbol_x = TRUE, 
  
  #Rename Title, for No title replace text with NULL
  caption = "Latency by Mind Wanderer, Congruent and Switch Trials")


mean_sd <- function(x) c(mean = mean(x), sd = sd(x))

average_rt_by_switch <- aggregate(latency ~ switch, data = Experiment3TS, FUN = mean_sd)

Experiment3TS$RT_long <- ifelse(Experiment3TS$switch == 1 & Experiment3TS$latency > 2000,1,ifelse(Experiment3TS$switch == 0 & Experiment3TS$latency > 1200,1,0))

RT_long <- Experiment3TS %>% filter(RT_long == 1)

LongCount <- RT_long %>% group_by(subject, switch, congruence, MWer) %>% summarise(count_1 = sum(RT_long == 1, na.rm = TRUE))

ggplot(LongCount, aes(x = count_1, fill = MWer)) +
  geom_density(alpha=0.2)

average_rtLong_by_switch <- aggregate(latency ~ switch+subject+MWer, data = RT_long, FUN = mean)

ggplot(average_rtLong_by_switch, aes(x = latency, fill = MWer)) +
  geom_density(alpha=0.2)

#Exp3TSpost <- 

participant_avg_latency <- Experiment3TS %>%
  group_by(subject, switch) %>%
  summarize(avg_latency = mean(latency),
            sd_latency = sd(latency))

# View the new dataframe
print(participant_avg_latency)

RTbyMWExp3TSswitch <- ggplot(participant_avg_latency, aes(x = switch, y = avg_latency, fill = switch)) + 
  geom_violin(trim = FALSE) +
  labs(title = "Reaction Time of Task Switching Between Switch Conditions", 
       x = "Switch", 
       y = "Average Task Switching Reaction Time",
       fill = "Switch") +
  scale_x_discrete(labels = c("0" = "Non-Switch Trial", "1" = "Switch Trial")) +
  scale_fill_manual(values = c("0" = "blue", "1" = "red"),
                    labels = c("0" = "Non-Switch Trial", "1" = "Switch Trial"))

RTbyMWExp3TSswitch + stat_summary(fun.data="mean_sdl", mult=1,
                                  geom="crossbar", width=0.2, ,stackdir='center',
                                  position=position_dodge(.9))
RTbyMWExp3TSswitch + stat_summary(fun.data=mean_sdl, mult=1,
                                  geom="pointrange", color="black", stackdir='center',
                                  position=position_dodge(.9))

RTbyMWExp3TSswitch <- ggplot(Experiment3TS, aes(x = switch, y = latency, fill = switch)) +
  stat_summary(
    fun = "mean", 
    geom = "bar", 
    position = position_dodge(width = 0.9),
    aes(label = round(..y.., digits = 2)),
    vjust = -0.5
  ) +
  geom_text(
    stat = "summary", 
    fun = "mean", 
    aes(label = round(..y.., digits = 3)),
    position = position_dodge(width = 0.9),
    vjust = -0.5
  ) +
  labs(
    x = "Switch",
    y = "Average Task Switching Reaction Time"
  ) +
  ggtitle(str_wrap("Reaction Time of Task Switching Between Switch Conditions", width = 70)) +
  theme_minimal() +
  theme(plot.title = element_text(margin = margin(b = 5)))  # Adjust the bottom margin of the title


# Print the plot
RTbyMWExp3TSswitch

summary(lmer(latency~congruence*switch + (1|subject), data = Experiment3TS))
summary(lmer(latency~MWer*switch + (1|subject), data = Experiment3TS))
summary(lmer(latency~MWer + (1|subject), data = Experiment3TS))

TSacc <- lmer(correct~new_cond_column*MWer*congruence*switch + (1|subject), data = Experiment3TS)
TSaccConfInt <- confint(TSacc)
TSaccLMERresults <- summary(TSacc)
frequentist_model_table(TSaccLMERresults, TSaccConfInt,
 # Replace colons in the names of interactions with times symbols
  interaction_symbol_x = TRUE, 
  
  #Rename Title, for No title replace text with NULL
  caption = "Accuracy by Enjoyment Condition, Mind Wanderer, Congruent and Switch Trials")

TSacc <- lmer(correct~new_cond_column+MWer+congruence+switch + (1|subject), data = Experiment3TS)
TSaccConfInt <- confint(TSacc)
TSaccLMERresults <- summary(TSacc)
frequentist_model_table(TSaccLMERresults, TSaccConfInt,
 # Replace colons in the names of interactions with times symbols
  interaction_symbol_x = TRUE, 
  
  #Rename Title, for No title replace text with NULL
  caption = "Accuracy by Enjoyment Condition, Mind Wanderer, Congruent and Switch Trials")




TSacc <- lmer(correct~new_cond_column*congruence*switch + (1|subject), data = Experiment3TS)
TSaccConfInt <- confint(TSacc)
TSaccLMERresults <- summary(TSacc)
frequentist_model_table(TSaccLMERresults, TSaccConfInt,
 # Replace colons in the names of interactions with times symbols
  interaction_symbol_x = TRUE, 
  
  #Rename Title, for No title replace text with NULL
  caption = "Accuracy by Mind Wanderer, Congruent and Switch Trials")

TSacc <- lmer(correct~new_cond_column+congruence+switch + (1|subject), data = Experiment3TS)
TSaccConfInt <- confint(TSacc)
TSaccLMERresults <- summary(TSacc)
frequentist_model_table(TSaccLMERresults, TSaccConfInt,
 # Replace colons in the names of interactions with times symbols
  interaction_symbol_x = TRUE, 
  
  #Rename Title, for No title replace text with NULL
  caption = "Accuracy by Mind Wanderer, Congruent and Switch Trials")

average_acc_by_switch <- aggregate(correct ~ switch, data = Experiment3TS, FUN = mean_sd)
average_acc_by_cong <- aggregate(correct ~ congruence, data = Experiment3TS, FUN = mean_sd)

participant_avg_acc_switch <- Experiment3TS %>%
  group_by(subject, switch) %>%
  summarize(avg_correct = mean(correct))

# View the new dataframe
print(participant_avg_acc_switch)

ACCbyMWExp3TSswitch <- ggplot(participant_avg_acc_switch, aes(x = switch, y = avg_correct, fill = switch)) + 
  geom_violin(trim = FALSE) +
  labs(title = "Accuracy of Task Switching Between Switch Conditions", 
       x = "Switch", 
       y = "Average Task Switching Accuracy",
       fill = "Switch") +
  scale_x_discrete(labels = c("0" = "Non-Switch Trial", "1" = "Switch Trial")) +
  scale_fill_manual(values = c("0" = "blue", "1" = "red"),
                    labels = c("0" = "Non-Switch Trial", "1" = "Switch Trial"))

ACCbyMWExp3TSswitch + stat_summary(fun.data="mean_sdl", mult=1,
                                  geom="crossbar", width=0.2, ,stackdir='center',
                                  position=position_dodge(.9))
ACCbyMWExp3TSswitch + stat_summary(fun.data=mean_sdl, mult=1,
                                  geom="pointrange", color="black", stackdir='center',
                                  position=position_dodge(.9))



ACCbyMWExp3TS <- ggplot(Experiment3TS, aes(x = MWer, y = correct, fill = MWer)) +
  stat_summary(
    fun = "mean", 
    geom = "bar", 
    position = position_dodge(width = 0.9),
    aes(label = round(..y.., digits = 2)),
    vjust = -0.5
  ) +
  geom_text(
    stat = "summary", 
    fun = "mean", 
    aes(label = round(..y.., digits = 3)),
    position = position_dodge(width = 0.9),
    vjust = -0.5
  ) +
  labs(
    x = "Mind Wanderer",
    y = "Average Task Switching Accuracy"
  ) +
  ggtitle(str_wrap("Accuracy of Task Switching Between Mind Wanderers", width = 70)) +
  theme_minimal() +
  theme(plot.title = element_text(margin = margin(b = 5)))  # Adjust the bottom margin of the title


# Print the plot
ACCbyMWExp3TS

participant_avg_acc_congruent <- Experiment3TS %>%
  group_by(subject, congruence) %>%
  summarize(avg_correct = mean(correct))

# View the new dataframe
print(participant_avg_acc_congruent)

ACCbyMWExp3TScong <- ggplot(participant_avg_acc_congruent, aes(x = congruence, y = avg_correct, fill = congruence)) +   geom_violin(trim = FALSE) +
  labs(title = "Accuracy of Responses Between Congruent Trials", 
       x = "Congruence", 
       y = "Average Congruent Trial Accuracy",
       fill = "Congruence") +
  scale_x_discrete(labels = c("1" = "Congruent", "2" = "Incongruent")) +
  scale_fill_manual(values = c("1" = "blue", "2" = "red"),
                    labels = c("1" = "Congruent", "2" = "Incongruent"))

ACCbyMWExp3TScong + stat_summary(fun.data="mean_sdl", mult=1,
                                  geom="crossbar", width=0.2, ,stackdir='center',
                                  position=position_dodge(.9))
ACCbyMWExp3TScong + stat_summary(fun.data=mean_sdl, mult=1,
                                  geom="pointrange", color="black", stackdir='center',
                                  position=position_dodge(.9))


ACCbyMWExp3TScongruence <- ggplot(Experiment3TS, aes(x = congruence, y = correct, fill = congruence)) +
  stat_summary(
    fun = "mean", 
    geom = "bar", 
    position = position_dodge(width = 0.9),
    aes(label = round(..y.., digits = 2)),
    vjust = -0.5
  ) +
  geom_text(
    stat = "summary", 
    fun = "mean", 
    aes(label = round(..y.., digits = 3)),
    position = position_dodge(width = 0.9),
    vjust = -0.5
  ) +
  labs(
    x = "Congruence",
    y = "Average Task Switching Accuracy"
  ) +
  ggtitle(str_wrap("Accuracy of Task Switching Between Congruent Trials", width = 70)) +
  theme_minimal() +
  theme(plot.title = element_text(margin = margin(b = 5)))  # Adjust the bottom margin of the title


# Print the plot
ACCbyMWExp3TScongruence

ACCbyMWExp3TSswitch <- ggplot(Experiment3TS, aes(x = switch, y = correct, fill = switch)) +
  stat_summary(
    fun = "mean", 
    geom = "bar", 
    position = position_dodge(width = 0.9),
    aes(label = round(..y.., digits = 2)),
    vjust = -0.5
  ) +
  geom_text(
    stat = "summary", 
    fun = "mean", 
    aes(label = round(..y.., digits = 3)),
    position = position_dodge(width = 0.9),
    vjust = -0.5
  ) +
  labs(
    x = "Switch",
    y = "Average Task Switching Accuracy"
  ) +
  ggtitle(str_wrap("Accuracy of Task Switching Between Switch Trials", width = 70)) +
  theme_minimal() +
  theme(plot.title = element_text(margin = margin(b = 5)))  # Adjust the bottom margin of the title


# Print the plot
ACCbyMWExp3TSswitch

summary(lmer(correct~congruence*switch + (1|subject), data = Experiment3TS))
summary(lmer(correct~MWer*congruence + (1|subject), data = Experiment3TS))
summary(lmer(correct~MWer + (1|subject), data = Experiment3TS))


PaidbyMWExp3TS <- ggplot(MWTS_groupings, aes(x = MWer, y = paid_response, fill = MWer)) +
  stat_summary(
    fun = "mean", 
    geom = "bar", 
    position = position_dodge(width = 0.9),
    aes(label = round(..y.., digits = 2)),
    vjust = -0.5
  ) +
  geom_text(
    stat = "summary", 
    fun = "mean", 
    aes(label = round(..y.., digits = 3)),
    position = position_dodge(width = 0.9),
    vjust = -0.5
  ) +
  labs(
    x = "Mind Wanderer",
    y = "Average Amount to be Paid"
  ) +
  ggtitle(str_wrap("Average Amount of Payment Required to Continue Between Mind Wanderers", width = 70)) +
  theme_minimal() +
  theme(plot.title = element_text(margin = margin(b = 5)))  # Adjust the bottom margin of the title


# Print the plot
PaidbyMWExp3TS


#SART Processing
Experiment3SART <- df %>% filter(new_exp_column == "EXP3-SART")
Experiment3SART <- Experiment3SART %>% filter(blockcode == "SART")

#Mind Wandering Assignment
#Add in Mind Wandering Variable
SARTMindWander <- Experiment3SART[!duplicated(Experiment3SART$subject), ]

# Create a function to process each subject
process_subject <- function(subject_data) {
  # Count the number of "Yes" and "No" responses
  yes_count <- sum(subject_data$probe_response == "Yes")
  no_count <- sum(subject_data$probe_response == "No")
  
  # Compare counts and assign a value based on the majority response
  if (yes_count > no_count) {
    result <- "Yes"
  } else if (yes_count < no_count) {
    result <- "No"
  } else {
    result <- "Tie"  # Handle tie situations if needed
  }
  
  return(result)
}

# Iterate through subjects and process each one
resultsSART <- sapply(split(SARTMindWander, SARTMindWander$subject), process_subject)

# Display the results
result_dataSART <- data.frame(subject = names(resultsSART), MWer = resultsSART)
print(result_dataSART)
result_dataSART %>% count(MWer)
result_dataSART$subject <- as.integer(result_dataSART$subject)



###SART analysis for Exp3
Experiment3SART <- left_join(Experiment3SART, result_dataSART, by = "subject")

Experiment3SARTprobeResp <- distinct(Experiment3TS, subject, .keep_all = TRUE)

title <- "Proportion of Responses to the Mind Wandering Probes For the SART by Enjoyment Condition"
postProbeSART <- ggplot(data = Experiment3SARTprobeResp)+
geom_mosaic(aes(x = product(probe_response, new_cond_column), fill=new_cond_column), na.rm=TRUE) +
  labs(
    x = "Enjoyment Condition",
    y = "Responses to Mind Wandering Probe") +
    ggtitle(title) +
  guides(fill = "none")
postProbeSART

Experiment3SARTprobeResp %>% group_by(new_cond_column) %>% count(probe_response)

TSsartbothPlots <- grid.arrange(postProbeTS, postProbeSART, ncol = 2)
#ggsave("arranged_plots.png", bothPlots, width = 12, height = 6, units = "in", dpi = 300)

grid.arrange(postProbeTS, postProbeSART, ncol = 2)

####Analysis of SART Performance
Experiment3SART$hit <- ifelse(Experiment3SART$trialtype == "NoGo" & Experiment3SART$correct == 1, 1, 0)
Experiment3SART$miss <- ifelse(Experiment3SART$trialtype == "NoGo" & Experiment3SART$correct == 0, 1, 0)
Experiment3SART$CR <- ifelse(Experiment3SART$trialtype == "Go" & Experiment3SART$correct == 1, 1, 0)
Experiment3SART$FA <- ifelse(Experiment3SART$trialtype == "Go" & Experiment3SART$correct == 0, 1, 0)


Exp3SARTrtFilt <- Experiment3SART %>% filter(correct == 1)
Exp3SARTrtFilt <- Experiment3SART %>% filter(trialtype == "Go")
Exp3SARTfaFilt <- Experiment3SART %>% filter(trialtype == "Go")

Exp3SARTaccFilt <- Experiment3SART %>% filter(trialtype == "NoGo")
Exp3SARTmissFilt <- Experiment3SART %>% filter(trialtype == "NoGo")


Exp3FAmean <- aggregate(FA ~ subject + new_exp_column + new_cond_column, Exp3SARTfaFilt, mean)
Exp3Hitmean <- aggregate(correct ~ subject + new_exp_column + new_cond_column, Exp3SARTaccFilt, mean)
Exp3Missmean <- aggregate(CR ~ subject + new_exp_column + new_cond_column, Exp3SARTrtFilt, mean)
Exp3RTmean <- aggregate(latency ~ subject + new_exp_column + new_cond_column, Exp3SARTrtFilt, mean)

Exp3QualCheck <- left_join(Exp3Hitmean, Exp3FAmean, by = "subject") %>%
  left_join(Exp3Missmean, by = "subject") %>%
  left_join(Exp3RTmean, by = "subject")
# 538020870 did not respond to 50% of the task.  However, it isn't as if they walked away, they just randomly did not respond, and when they did respond,it was distributed between the no-go and go trials.  

###Analysis of RT for SART
# Exp3RTlm <- lm(latency~new_cond_column*MWer, data = Exp3SARTrtFilt)
# summary(Exp3RTlm)

Exp3RTlm <- lmer(latency~new_cond_column + (1 | subject), data=Exp3SARTrtFilt)
summary(Exp3RTlm)

average_rt_by_sart <- aggregate(latency ~ new_cond_column + MWer, data = Exp3SARTrtFilt, FUN = mean_sd)

Exp3RTConfInt <- confint(Exp3RTlm)
Exp3RTLMERresults <- summary(Exp3RTlm)
frequentist_model_table(Exp3RTLMERresults, Exp3RTConfInt,
 # Replace colons in the names of interactions with times symbols
  interaction_symbol_x = TRUE, 
  
  #Rename Title, for No title replace text with NULL
  caption = "SART Latency by Mind Wanderer, Congruenct and Switch Trials")

Exp3RTlm <- lmer(latency~new_cond_column * MWer + (1 | subject), data=Exp3SARTrtFilt)
summary(Exp3RTlm)

participant_avg_rt_SART <- Exp3SARTrtFilt %>%
  group_by(subject, new_cond_column, MWer) %>%
  summarize(avg_latency = mean(latency))

# View the new dataframe
print(participant_avg_rt_SART)

ACCbyMWExp3RTSART <- ggplot(participant_avg_rt_SART, aes(x = new_cond_column, y = avg_latency, fill = MWer)) + 
  geom_violin(trim = FALSE) +
  labs(title = "Average Latency of Responses for Go Trials by Mind Wanderer and Enjoyment Condition", 
       x = "Enjoyment Condition", 
       y = "Average Latency of Go Trials",
       fill = "Mind Wanderer") +
  scale_x_discrete(labels = c("Enjoy" = "Enjoy", "NotEnjoy" = "Not Enjoy")) +
  scale_fill_manual(values = c("Yes" = "blue", "No" = "red"),
                    labels = c("Yes" = "Mind Wanderer", "No" = "Not Mind Wanderer"))

ACCbyMWExp3RTSART + stat_summary(fun.data="mean_sdl", mult=1,
                                  geom="crossbar", width=0.2, stackdir='center',
                                  position=position_dodge(.9))
ACCbyMWExp3RTSART + stat_summary(fun.data=mean_sdl, mult=1,
                                  geom="pointrange", color="black", stackdir='center',
                                  position=position_dodge(.9))



Exp3RTConfInt <- confint(Exp3RTlm)
Exp3RTLMERresults <- summary(Exp3RTlm)
frequentist_model_table(Exp3RTLMERresults, Exp3RTConfInt,
 # Replace colons in the names of interactions with times symbols
  interaction_symbol_x = TRUE, 
  
  #Rename Title, for No title replace text with NULL
  caption = "SART Latency by Mind Wanderer, Congruenct and Switch Trials")

Exp3RTlm <- lmer(latency~new_cond_column + MWer + (1 | subject), data=Exp3SARTrtFilt)
summary(Exp3RTlm)

Exp3RTConfInt <- confint(Exp3RTlm)
Exp3RTLMERresults <- summary(Exp3RTlm)
frequentist_model_table(Exp3RTLMERresults, Exp3RTConfInt,
 # Replace colons in the names of interactions with times symbols
  interaction_symbol_x = TRUE, 
  
  #Rename Title, for No title replace text with NULL
  caption = "SART Latency by Mind Wanderer and Enjoyment Condition")


Exp3RTbyGroup <- ggplot(Exp3SARTrtFilt, aes(x = new_cond_column, y = latency, fill = MWer)) +
    stat_summary(
    fun = "mean", 
    geom = "bar", 
    position = position_dodge(width = 0.9),
    aes(label = round(..y.., digits = 2)),
    vjust = -0.5
  ) +
  geom_text(
    stat = "summary", 
    fun = "mean", 
    aes(label = round(..y.., digits = 2)),
    position = position_dodge(width = 0.9),
    vjust = -0.5
  ) +
  labs(
   x = "Enjoyment Condition",
    y = "Average Reaction Time",
    title = "Average Reaction Time Between Enjoyment Conditions and Mind Wanderer"
  ) +
  theme_minimal()
Exp3RTbyGroup


Exp3RTbyConditionsInt <- Exp3SARTrtFilt %>%
  group_by(new_cond_column, MWer) %>%
  summarize(mean_value = mean(latency))
print(Exp3RTbyConditionsInt)

#####Analysis of ACC for SART NoGo Trials
# Exp3ACClm <- lm(correct ~ new_cond_column*MWer, data = Exp3SARTaccFilt)
# summary(Exp3ACClm)

Exp3ACClm <- lmer(correct~new_cond_column * MWer + (1 | subject), data=Exp3SARTaccFilt)
summary(Exp3ACClm)

Exp3ACCConfInt <- confint(Exp3ACClm)
Exp3ACCLMERresults <- summary(Exp3ACClm)
frequentist_model_table(Exp3ACCLMERresults, Exp3ACCConfInt,
 # Replace colons in the names of interactions with times symbols
  interaction_symbol_x = TRUE, 
  
  #Rename Title, for No title replace text with NULL
  caption = "SART Accuracy by Mind Wanderer and Enjoyment Conditions")

Exp3ACClm <- lmer(correct~new_cond_column + MWer + (1 | subject), data=Exp3SARTaccFilt)
summary(Exp3ACClm)

Exp3ACCConfInt <- confint(Exp3ACClm)
Exp3ACCLMERresults <- summary(Exp3ACClm)
frequentist_model_table(Exp3ACCLMERresults, Exp3ACCConfInt,
 # Replace colons in the names of interactions with times symbols
  interaction_symbol_x = TRUE, 
  
  #Rename Title, for No title replace text with NULL
  caption = "SART Accuracy by Mind Wanderer and Enjoyment Conditions")

average_acc_by_sart <- aggregate(correct ~ new_cond_column + MWer, data = Exp3SARTaccFilt, FUN = mean_sd)

participant_avg_acc_SART <- Exp3SARTaccFilt %>%
  group_by(subject, new_cond_column, MWer) %>%
  summarize(avg_accuracy = mean(correct))

# View the new dataframe
print(participant_avg_acc_SART)

ACCbyMWExp3ACCSART <- ggplot(participant_avg_acc_SART, aes(x = new_cond_column, y = avg_accuracy, fill = MWer)) + 
  geom_violin(trim = FALSE) +
  labs(title = "Average Accuracy of Responses for No Go Trials by Mind Wanderer and Enjoyment Condition", 
       x = "Enjoyment Condition", 
       y = "Average Accuracy of No Go Trials",
       fill = "Mind Wanderer") +
  scale_x_discrete(labels = c("Enjoy" = "Enjoy", "NotEnjoy" = "Not Enjoy")) +
  scale_fill_manual(values = c("Yes" = "blue", "No" = "red"),
                    labels = c("Yes" = "Mind Wanderer", "No" = "Not Mind Wanderer"))

ACCbyMWExp3ACCSART + stat_summary(fun.data="mean_sdl", mult=1,
                                  geom="crossbar", width=0.2, stackdir='center',
                                  position=position_dodge(.9))
ACCbyMWExp3ACCSART + stat_summary(fun.data=mean_sdl, mult=1,
                                  geom="pointrange", color="black", stackdir='center',
                                  position=position_dodge(.9))

Exp3ACCbyGroup <- ggplot(Exp3SARTaccFilt, aes(x = new_cond_column, y = correct, fill = MWer)) +
  stat_summary(
    fun = "mean", 
    geom = "bar", 
    position = position_dodge(width = 0.9),
    aes(label = round(..y.., digits = 2)),
    vjust = -0.5
  ) +
  geom_text(
    stat = "summary", 
    fun = "mean", 
    aes(label = round(..y.., digits = 2)),
    position = position_dodge(width = 0.9),
    vjust = -0.5
  ) +
  labs(
   x = "Enjoyment Condition",
    y = "Average Accuracy",
    title = "Average Accuracy of No Go Trials Between Enjoyment and Mind Wanderer"
  ) +
  theme_minimal()
Exp3ACCbyGroup

Exp3ACCbyConditionsInt <- Exp3SARTaccFilt %>%
  group_by(new_cond_column, MWer) %>%
  summarize(mean_value = mean(correct))
print(Exp3ACCbyConditionsInt)

Exp3SARTfaFilt <- Exp3SARTrtFilt
Exp3SARTmissFILT <- Exp3SARTaccFilt

#Remember*** I am interpreting the target (No Go trials) as hits.  So withholding a response on a Go trial would be an FA
# Exp3FAlm <- lm(FA ~ new_cond_column*MWer, data = Exp3SARTfaFilt)
# summary(Exp3FAlm)

Exp3FAlm <- lmer(FA~new_cond_column * MWer + (1 | subject), data=Exp3SARTfaFilt)
summary(Exp3FAlm)

Exp3FAConfInt <- confint(Exp3FAlm)
Exp3FALMERresults <- summary(Exp3FAlm)
frequentist_model_table(Exp3FALMERresults, Exp3FAConfInt,
 # Replace colons in the names of interactions with times symbols
  interaction_symbol_x = TRUE, 
  
  #Rename Title, for No title replace text with NULL
  caption = "SART False Alarms by Mind Wanderer and Enjoyment Condition")

Exp3FAlm <- lmer(FA~new_cond_column + MWer + (1 | subject), data=Exp3SARTfaFilt)
summary(Exp3FAlm)

Exp3FAConfInt <- confint(Exp3FAlm)
Exp3FALMERresults <- summary(Exp3FAlm)
frequentist_model_table(Exp3FALMERresults, Exp3FAConfInt,
 # Replace colons in the names of interactions with times symbols
  interaction_symbol_x = TRUE, 
  
  #Rename Title, for No title replace text with NULL
  caption = "SART False Alarms by Mind Wanderer and Enjoyment Condition")

average_fa_by_sart <- aggregate(FA ~ new_cond_column + MWer, data = Exp3SARTfaFilt, FUN = mean_sd)

participant_avg_fa_SART <- Exp3SARTfaFilt %>%
  group_by(subject, new_cond_column, MWer) %>%
  summarize(avg_fa = mean(FA))

# View the new dataframe
print(participant_avg_fa_SART)

ACCbyMWExp3FASART <- ggplot(participant_avg_fa_SART, aes(x = new_cond_column, y = avg_fa, fill = MWer)) + 
  geom_violin(trim = FALSE) +
  labs(title = "Average False Alarm Rate by Mind Wanderer and Enjoyment Condition", 
       x = "Enjoyment Condition", 
       y = "Average False Alarm Rate",
       fill = "Mind Wanderer") +
  scale_x_discrete(labels = c("Enjoy" = "Enjoy", "NotEnjoy" = "Not Enjoy")) +
  scale_fill_manual(values = c("Yes" = "blue", "No" = "red"),
                    labels = c("Yes" = "Mind Wanderer", "No" = "Not Mind Wanderer"))

ACCbyMWExp3FASART + stat_summary(fun.data="mean_sdl", mult=1,
                                  geom="crossbar", width=0.2, stackdir='center',
                                  position=position_dodge(.9))
ACCbyMWExp3FASART + stat_summary(fun.data=mean_sdl, mult=1,
                                  geom="pointrange", color="black", stackdir='center',
                                  position=position_dodge(.9))

Exp3FAbyGroup <- ggplot(Exp3SARTfaFilt, aes(x = new_cond_column, y = FA, fill = MWer)) +
  stat_summary(
    fun = "mean", 
    geom = "bar", 
    position = position_dodge(width = 0.9),
    aes(label = round(..y.., digits = 2)),
    vjust = -0.5
  ) +
  geom_text(
    stat = "summary", 
    fun = "mean", 
    aes(label = round(..y.., digits = 3)),
    position = position_dodge(width = 0.9),
    vjust = -0.5
  ) +
  labs(
   x = "Enjoyment Condition",
    y = "Average False Alarms",
    title = "Average False Alarms of Go Trials Between Enjoyment Conditions and Mind Wanderer"
  ) +
  theme_minimal()
Exp3FAbyGroup

Exp3FAbyConditionsInt <- Exp3SARTfaFilt %>%
  group_by(new_cond_column, MWer) %>%
  summarize(mean_value = mean(FA))
print(Exp3FAbyConditionsInt)

Exp3MISSbyGroup <- ggplot(Exp3SARTmissFILT, aes(x = new_cond_column, y = miss, fill = MWer)) +
  stat_summary(
    fun = "mean", 
    geom = "bar", 
    position = position_dodge(width = 0.9),
    aes(label = round(..y.., digits = 2)),
    vjust = -0.5
  ) +
  geom_text(
    stat = "summary", 
    fun = "mean", 
    aes(label = round(..y.., digits = 3)),
    position = position_dodge(width = 0.9),
    vjust = -0.5
  ) +
  labs(
   x = "Enjoyment Condition",
    y = "Average Misses",
    title = "Average Misses for No Go Trials Between Enjoyment Conditions and Mind Wanderer"
  ) +
  theme_minimal()
Exp3MISSbyGroup

Exp3MissbyConditionsInt <- Exp3SARTmissFILT %>%
  group_by(new_cond_column, MWer) %>%
  summarize(mean_value = mean(miss))


Exp3CRbyGroup <- ggplot(Exp3SARTfaFilt, aes(x = new_cond_column, y = CR, fill = MWer)) +
  stat_summary(
    fun = "mean", 
    geom = "bar", 
    position = position_dodge(width = 0.9),
    aes(label = round(..y.., digits = 2)),
    vjust = -0.5
  ) +
  geom_text(
    stat = "summary", 
    fun = "mean", 
    aes(label = round(..y.., digits = 3)),
    position = position_dodge(width = 0.9),
    vjust = -0.5
  ) +
  labs(
   x = "Enjoyment Condition",
    y = "Average Correct Rejections",
    title = "Average Correct Rejections of Go Trials Between Enjoyment Conditions and Mind Wanderer"
  ) +
  theme_minimal()
Exp3CRbyGroup

Exp3CRbyConditionsInt <- Exp3SARTfaFilt %>%
  group_by(new_cond_column, MWer) %>%
  summarize(mean_value = mean(CR))

#The misses and CR analyses are appearing as I expected.  The graphs and tables are just the inverse from the analyses of FAs and Hits.  I'm just going to 





```

```{r Analysis of corrected EFA}
# ##################################################################################################################
# #These are my analyses for Post Task Surveys
# ##################################################################################################################

library(corrr)
library(ggcorrplot)
library(FactoMineR)
library(psych)
library(GPArotation)

##########MW Response Analysis#######################

SurveyAnalysis <- df

MWerResultsData <- rbind(MWresult_dataExp1Exp2, result_dataSART, result_dataTS)

SurveyAnalysis <- left_join(SurveyAnalysis, MWerResultsData, by = "subject")
SurveyAnalysis <- SurveyAnalysis %>% filter(!is.na(MWer))
length(unique(SurveyAnalysis$subject))

#NASA-TLX Transformations
SurveyAnalysis <- SurveyAnalysis %>%
  mutate(mentaldemand_response_coded = (mentaldemand_response - 1) * 5)


SurveyAnalysis <- SurveyAnalysis %>%
  mutate(physicaldemand_response_coded = (physicaldemand_response - 1) * 5)


SurveyAnalysis <- SurveyAnalysis %>%
  mutate(temporaldemand_response_coded = (temporaldemand_response - 1) * 5)


SurveyAnalysis <- SurveyAnalysis %>%
  mutate(performance_response_coded = (performance_response - 1) * 5)


SurveyAnalysis <- SurveyAnalysis %>%
  mutate(effort_response_coded = (effort_response - 1) * 5)

SurveyAnalysis <- SurveyAnalysis %>%
  mutate(frustration_response_coded = (frustration_response - 1) * 5)


PostSurveys <- SurveyAnalysis[!duplicated(SurveyAnalysis$subject), ]

PostSurveys$difficulty_responseNum <- ifelse(PostSurveys$difficulty_response == 'Very Difficult', 1, ifelse(PostSurveys$difficulty_response == 'Difficult', 2, ifelse(PostSurveys$difficulty_response == 'Neither Easy/Difficult', 3, ifelse(PostSurveys$difficulty_response == 'Easy', 4, ifelse(PostSurveys$difficulty_response == 'Very Easy', 5, 999)))))


PostSurveys$interest_responseNum <- ifelse(PostSurveys$interest_response == 'Not at all interesting', 1, ifelse(PostSurveys$interest_response == 'A little interesting', 2, ifelse(PostSurveys$interest_response == 'Somewhat interesting', 3, ifelse(PostSurveys$interest_response == 'Pretty interesting', 4, ifelse(PostSurveys$interest_response == 'Highly Interesting', 5, 999)))))

PostSurveys <- PostSurveys %>% filter(MWer != "Tie")


ggplot(PostSurveys, aes(x = paid_response, fill = new_exp_column)) +
  geom_density(alpha=0.2)

ggplot(PostSurveys, aes(x = paid_response, fill = MWer)) +
  geom_density(alpha=0.2)

MWprobePlace <- ggplot(data = PostSurveys, aes(x = new_exp_column, y = paid_response, fill = MWer)) +
  geom_bar(stat = "summary", fun = "mean", position = "dodge") + 
  scale_fill_manual(values = c("Yes" = "blue", "No" = "red"))
MWprobePlace


MWprobePlace.labs <- MWprobePlace + labs(title = "Average Amount to be Paid by Experiment", x = "Experimental Condition", y = "Average Amount to be Paid") + scale_x_discrete(limit = c("EXP1", "EXP2", "EXP3-TS", "EXP3-SART"), labels = c("Interrupting Probe","Retrospective Probe", "Task Switching Paradigm", "SART"))
MWprobePlace.labs


colnames(PostSurveys)

pcadf <- PostSurveys[, c(82, 103, 104, 105, 106, 107, 108, 109, 110)]

model = fa(pcadf, 5, rotate="varimax")
model
model$loadings
model$scores
model$r.scores
modelResults <- model$scores
model$scor
model$uniquenesses

plot(1:length(model$e.values), model$e.values, type = "b", 
     xlab = "Factor Number", ylab = "Eigenvalue",
     main = "Scree Plot")

EFAanalysis <- cbind(PostSurveys, modelResults)
summary(lm(MR1 ~ new_exp_column*new_cond_column*MWer, data= EFAanalysis))
summary(lm(MR1 ~ new_exp_column*MWer, data= EFAanalysis))
summary(lm(MR1 ~ new_cond_column*MWer, data= EFAanalysis))
summary(lm(MR1 ~ new_exp_column, data= EFAanalysis))
summary(lm(MR1 ~ new_cond_column, data= EFAanalysis))
summary(lm(MR1 ~ MWer, data= EFAanalysis))
summary(lm(MR2 ~ new_exp_column*new_cond_column*MWer, data= EFAanalysis))
summary(lm(MR3 ~ new_exp_column*new_cond_column*MWer, data= EFAanalysis))
summary(lm(MR4 ~ new_exp_column*new_cond_column*MWer, data= EFAanalysis))
summary(lm(MR5 ~ new_exp_column*new_cond_column*MWer, data= EFAanalysis))

ggplot(EFAanalysis, aes(x = MR1, color = MWer)) +
   geom_density()

ggplot(EFAanalysis, aes(x = MR2, color = MWer)) +
   geom_density()


table(EFAanalysis$difficulty_responseNum)
table(EFAanalysis$interest_responseNum)
table(EFAanalysis$effort_response_coded)
table(EFAanalysis$physicaldemand_response_coded)
table(EFAanalysis$temporaldemand_response_coded)
table(EFAanalysis$performance_response_coded)
table(EFAanalysis$frustration_response_coded)
table(EFAanalysis$GTQ_response)
table(EFAanalysis$MWer)

#Tables for the raw EFA scores based on MW assignment and MW assignment by Enjoyable condition
MWerAndEnjoyableConditionByFactorLoadings <- EFAanalysis %>%
  group_by(MWer, new_exp_column, new_cond_column) %>%
  summarise(
    avg_MR1 = mean(MR1))

MWerAndEnjoyableConditionByFactorLoadings

MWerAndEnjoyableConditionByFactorLoadings2 <- EFAanalysis %>%
  group_by(MWer, new_exp_column, new_cond_column) %>%
  summarise(
    avg_MR1 = mean(MR5))

MWerAndEnjoyableConditionByFactorLoadings2


#Tables for the raw Mental Demand Coded Scores by MW assignment and Enjoyment Condition
MWerByMentalDemand  <- EFAanalysis %>%
  group_by(MWer, new_exp_column, new_cond_column) %>%
  summarise(
    avg_MentalDemand = mean(mentaldemand_response_coded))


ggplot(EFAanalysis, aes(x = mentaldemand_response_coded)) +
  geom_histogram(binwidth = 5, fill = "skyblue", color = "black", alpha = 0.7) +
  labs(title = "Histogram of Mental Demand", x = "Value", y = "Frequency") +
  theme_minimal()

ggplot(EFAanalysis, aes(x = mentaldemand_response_coded, color = MWer)) +
  geom_density()

mentalwide_data <- EFAanalysis %>%
  group_by(new_exp_column, MWer) %>%
  summarise(mean_value = mean(mentaldemand_response_coded),
            sd_value = sd(mentaldemand_response_coded)) %>%
  pivot_wider(names_from = MWer, values_from = c(mean_value, sd_value),
              names_glue = "{.value}_{MWer}")

mentallong_data <- EFAanalysis %>%
  group_by(new_exp_column, MWer) %>%
  summarise(
    N = length(MWer),
    mean_value = mean(mentaldemand_response_coded),
    sd_value = sd(mentaldemand_response_coded, na.rm = TRUE),
    se_value = sd_value/sqrt(N),
    ciMult = qt(0.95/2 + .5, N-1),
    ci = se_value*ciMult
  )

ggplot(mentallong_data, aes(x = new_exp_column, y = mean_value, fill = MWer)) +
  geom_bar(stat = "summary", fun = "mean", position = "dodge") +
  scale_fill_manual(values = c("Yes" = "blue", "No" = "red")) +
  geom_errorbar(aes(ymin = mean_value - ci, ymax = mean_value + ci),
                position = position_dodge(1), width = 0.2) +
  labs(title = "Mental Demand Response Scores", x = "Experimental Condition", y = "Average Response Ratings", fill = "Mind Wanderer") +
  scale_x_discrete(labels = c("EXP1" = "Interrupting Probe",
                              "EXP2" = "Post Probe",
                              "EXP3-SART" = "SART",
                              "EXP3-TS" = "Letter/Number Task Switch"))

#Tables for the raw Physical Demand Coded Scores by MW assignment and Enjoyment Condition
MWerByPhysicalDemand <- EFAanalysis %>%
  group_by(MWer, new_exp_column, new_cond_column) %>%
  summarise(
    avg_PhysicalDemand = mean(physicaldemand_response_coded))

ggplot(EFAanalysis, aes(x = physicaldemand_response_coded)) +
  geom_histogram(binwidth = 5, fill = "skyblue", color = "black", alpha = 0.7) +
  labs(title = "Histogram of Physical Demand", x = "Value", y = "Frequency") +
  theme_minimal()

ggplot(EFAanalysis, aes(x = physicaldemand_response_coded, color = MWer)) +
  geom_density()

physicalwide_data <- EFAanalysis %>%
  group_by(new_exp_column, MWer) %>%
  summarise(mean_value = mean(physicaldemand_response_coded),
            sd_value = sd(physicaldemand_response_coded)) %>%
  pivot_wider(names_from = MWer, values_from = c(mean_value, sd_value),
              names_glue = "{.value}_{MWer}")

physicallong_data <- EFAanalysis %>%
  group_by(new_exp_column, MWer) %>%
  summarise(
    N = length(MWer),
    mean_value = mean(physicaldemand_response_coded),
    sd_value = sd(physicaldemand_response_coded, na.rm = TRUE),
    se_value = sd_value/sqrt(N),
    ciMult = qt(0.95/2 + .5, N-1),
    ci = se_value*ciMult
  )

ggplot(physicallong_data, aes(x = new_exp_column, y = mean_value, fill = MWer)) +
  geom_bar(stat = "summary", fun = "mean", position = "dodge") +
  scale_fill_manual(values = c("Yes" = "blue", "No" = "red")) +
  geom_errorbar(aes(ymin = mean_value - ci, ymax = mean_value + ci),
                position = position_dodge(1), width = 0.2) +
  labs(title = "Physical Demand Response Scores", x = "Experimental Condition", y = "Average Response Ratings", fill = "Mind Wanderer") +
  scale_x_discrete(labels = c("EXP1" = "Interrupting Probe",
                              "EXP2" = "Post Probe",
                              "EXP3-SART" = "SART",
                              "EXP3-TS" = "Letter/Number Task Switch"))

#Tables for the raw Temporal Demand Coded Scores by MW assignment and Enjoyment Condition
MWerBytemporaldemand <- EFAanalysis %>%
  group_by(MWer, new_exp_column, new_cond_column) %>%
  summarise(
    avg_TemporalDemand = mean(temporaldemand_response_coded))

ggplot(EFAanalysis, aes(x = temporaldemand_response_coded)) +
  geom_histogram(binwidth = 5, fill = "skyblue", color = "black", alpha = 0.7) +
  labs(title = "Histogram of Temporal Demand", x = "Value", y = "Frequency") +
  theme_minimal()

ggplot(EFAanalysis, aes(x = temporaldemand_response_coded, color = MWer)) +
  geom_density()

temporalwide_data <- EFAanalysis %>%
  group_by(new_exp_column, MWer) %>%
  summarise(mean_value = mean(temporaldemand_response_coded),
            sd_value = sd(temporaldemand_response_coded)) %>%
  pivot_wider(names_from = MWer, values_from = c(mean_value, sd_value),
              names_glue = "{.value}_{MWer}")

temporallong_data <- EFAanalysis %>%
  group_by(new_exp_column, MWer) %>%
  summarise(
    N = length(MWer),
    mean_value = mean(temporaldemand_response_coded),
    sd_value = sd(temporaldemand_response_coded, na.rm = TRUE),
    se_value = sd_value/sqrt(N),
    ciMult = qt(0.95/2 + .5, N-1),
    ci = se_value*ciMult
  )

ggplot(temporallong_data, aes(x = new_exp_column, y = mean_value, fill = MWer)) +
  geom_bar(stat = "summary", fun = "mean", position = "dodge") +
  scale_fill_manual(values = c("Yes" = "blue", "No" = "red")) +
  geom_errorbar(aes(ymin = mean_value - ci, ymax = mean_value + ci),
                position = position_dodge(1), width = 0.2) +
  labs(title = "Temporal Demand Response Scores", x = "Experimental Condition", y = "Average Response Ratings", fill = "Mind Wanderer") +
  scale_x_discrete(labels = c("EXP1" = "Interrupting Probe",
                              "EXP2" = "Post Probe",
                              "EXP3-SART" = "SART",
                              "EXP3-TS" = "Letter/Number Task Switch"))

#Tables for the raw Performance Coded Scores by MW assignment and Enjoyment Condition
MWerByperformance <- EFAanalysis %>%
  group_by(MWer, new_exp_column, new_cond_column) %>%
  summarise(
    avg_Performance = mean(performance_response_coded))

ggplot(EFAanalysis, aes(x = performance_response_coded)) +
  geom_histogram(binwidth = 5, fill = "skyblue", color = "black", alpha = 0.7) +
  labs(title = "Histogram of Performance Response", x = "Value", y = "Frequency") +
  theme_minimal()

ggplot(EFAanalysis, aes(x = performance_response_coded, color = MWer)) +
  geom_density()

performancewide_data <- EFAanalysis %>%
  group_by(new_exp_column, MWer) %>%
  summarise(mean_value = mean(performance_response_coded),
            sd_value = sd(performance_response_coded)) %>%
  pivot_wider(names_from = MWer, values_from = c(mean_value, sd_value),
              names_glue = "{.value}_{MWer}")

performancelong_data <- EFAanalysis %>%
  group_by(new_exp_column, MWer) %>%
  summarise(
    N = length(MWer),
    mean_value = mean(performance_response_coded),
    sd_value = sd(performance_response_coded, na.rm = TRUE),
    se_value = sd_value/sqrt(N),
    ciMult = qt(0.95/2 + .5, N-1),
    ci = se_value*ciMult
  )

ggplot(performancelong_data, aes(x = new_exp_column, y = mean_value, fill = MWer)) +
  geom_bar(stat = "summary", fun = "mean", position = "dodge") +
  scale_fill_manual(values = c("Yes" = "blue", "No" = "red")) +
  geom_errorbar(aes(ymin = mean_value - ci, ymax = mean_value + ci),
                position = position_dodge(1), width = 0.2) +
  labs(title = "Performance Response Scores", x = "Experimental Condition", y = "Average Response Ratings", fill = "Mind Wanderer") +
  scale_x_discrete(labels = c("EXP1" = "Interrupting Probe",
                              "EXP2" = "Post Probe",
                              "EXP3-SART" = "SART",
                              "EXP3-TS" = "Letter/Number Task Switch"))

#Tables for the raw Effort Coded Scores by MW assignment and Enjoyment Condition
MWerByeffort <- EFAanalysis %>%
  group_by(MWer, new_exp_column, new_cond_column) %>%
  summarise(
    avg_Effort = mean(effort_response_coded))

ggplot(EFAanalysis, aes(x = new_exp_column, y = effort_response_coded, fill = MWer)) +
  geom_bar(stat = "summary", fun = "mean", position = "dodge") +
  scale_fill_manual(values = c("Yes" = "blue", "No" = "red")) +
  labs(title = "Histogram of Effort Response", x = "Value", y = "Experiment") +
  theme_minimal()

ggplot(EFAanalysis, aes(x = effort_response_coded, color = MWer)) +
  geom_density()

effortwide_data <- EFAanalysis %>%
  group_by(new_exp_column, MWer) %>%
  summarise(mean_value = mean(effort_response_coded),
            sd_value = sd(effort_response_coded)) %>%
  pivot_wider(names_from = MWer, values_from = c(mean_value, sd_value),
              names_glue = "{.value}_{MWer}")

effortlong_data <- EFAanalysis %>%
  group_by(new_exp_column, MWer) %>%
  summarise(
    N = length(MWer),
    mean_value = mean(effort_response_coded),
    sd_value = sd(effort_response_coded, na.rm = TRUE),
    se_value = sd_value/sqrt(N),
    ciMult = qt(0.95/2 + .5, N-1),
    ci = se_value*ciMult
  )

ggplot(effortlong_data, aes(x = new_exp_column, y = mean_value, fill = MWer)) +
  geom_bar(stat = "summary", fun = "mean", position = "dodge") +
  scale_fill_manual(values = c("Yes" = "blue", "No" = "red")) +
  geom_errorbar(aes(ymin = mean_value - ci, ymax = mean_value + ci),
                position = position_dodge(1), width = 0.2) +
  labs(title = "Effort Response Scores", x = "Experimental Condition", y = "Average Response Ratings", fill = "Mind Wanderer") +
  scale_x_discrete(labels = c("EXP1" = "Interrupting Probe",
                              "EXP2" = "Post Probe",
                              "EXP3-SART" = "SART",
                              "EXP3-TS" = "Letter/Number Task Switch"))

#Tables for the raw Frustration Coded Scores by MW assignment and Enjoyment Condition
MWerByfrustration <- EFAanalysis %>%
  group_by(MWer, new_exp_column, new_cond_column) %>%
  summarise(
    avg_Frustration = mean(frustration_response_coded))

ggplot(EFAanalysis, aes(x = frustration_response_coded)) +
  geom_histogram(binwidth = 5, fill = "skyblue", color = "black", alpha = 0.7) +
  labs(title = "Histogram of Frustration Response", x = "Value", y = "Frequency") +
  theme_minimal()

ggplot(EFAanalysis, aes(x = frustration_response_coded, color = MWer)) +
  geom_density()

frustrationwide_data <- EFAanalysis %>%
  group_by(new_exp_column, MWer) %>%
  summarise(mean_value = mean(frustration_response_coded),
            sd_value = sd(frustration_response_coded)) %>%
  pivot_wider(names_from = MWer, values_from = c(mean_value, sd_value),
              names_glue = "{.value}_{MWer}")

frustrationlong_data <- EFAanalysis %>%
  group_by(new_exp_column, MWer) %>%
  summarise(
    N = length(MWer),
    mean_value = mean(frustration_response_coded),
    sd_value = sd(frustration_response_coded, na.rm = TRUE),
    se_value = sd_value/sqrt(N),
    ciMult = qt(0.95/2 + .5, N-1),
    ci = se_value*ciMult
  )

ggplot(frustrationlong_data, aes(x = new_exp_column, y = mean_value, fill = MWer)) +
  geom_bar(stat = "summary", fun = "mean", position = "dodge") +
  scale_fill_manual(values = c("Yes" = "blue", "No" = "red")) +
  geom_errorbar(aes(ymin = mean_value - ci, ymax = mean_value + ci),
                position = position_dodge(1), width = 0.2) +
  labs(title = "Frustration Response Scores", x = "Experimental Condition", y = "Average Response Ratings", fill = "Mind Wanderer") +
  scale_x_discrete(labels = c("EXP1" = "Interrupting Probe",
                              "EXP2" = "Post Probe",
                              "EXP3-SART" = "SART",
                              "EXP3-TS" = "Letter/Number Task Switch"))

#Tables for the raw Difficulty Response Scores by MW assignment and Enjoyment Condition
MWerBydifficulty <- EFAanalysis %>%
  group_by(MWer, new_exp_column, new_cond_column) %>%
  summarise(
    avg_Difficulty = mean(difficulty_responseNum))

ggplot(EFAanalysis, aes(x = difficulty_responseNum)) +
  geom_histogram(binwidth = 1, fill = "skyblue", color = "black", alpha = 0.7) +
  labs(title = "Histogram of Difficulty Response", x = "Value", y = "Frequency") +
  theme_minimal()

ggplot(EFAanalysis, aes(x = difficulty_responseNum, color = MWer)) +
  geom_density()

difficultywide_data <- EFAanalysis %>%
  group_by(new_exp_column, MWer) %>%
  summarise(mean_value = mean(difficulty_responseNum),
            sd_value = sd(difficulty_responseNum)) %>%
  pivot_wider(names_from = MWer, values_from = c(mean_value, sd_value),
              names_glue = "{.value}_{MWer}")

difficultylong_data <- EFAanalysis %>%
  group_by(new_exp_column, MWer) %>%
  summarise(
    N = length(MWer),
    mean_value = mean(difficulty_responseNum),
    sd_value = sd(difficulty_responseNum, na.rm = TRUE),
    se_value = sd_value/sqrt(N),
    ciMult = qt(0.95/2 + .5, N-1),
    ci = se_value*ciMult
  )

ggplot(difficultylong_data, aes(x = new_exp_column, y = mean_value, fill = MWer)) +
  geom_bar(stat = "summary", fun = "mean", position = "dodge") +
  scale_fill_manual(values = c("Yes" = "blue", "No" = "red")) +
  geom_errorbar(aes(ymin = mean_value - ci, ymax = mean_value + ci),
                position = position_dodge(1), width = 0.2) +
  labs(title = "Difficulty Response Scores", x = "Experimental Condition", y = "Average Response Ratings", fill = "Mind Wanderer") +
  scale_x_discrete(labels = c("EXP1" = "Interrupting Probe",
                              "EXP2" = "Post Probe",
                              "EXP3-SART" = "SART",
                              "EXP3-TS" = "Letter/Number Task Switch"))


#Tables for the raw Interest Response Scores by MW assignment and Enjoyment Condition
MWerByinterest <- EFAanalysis %>%
  group_by(MWer, new_exp_column, new_cond_column) %>%
  summarise(
    avg_Interest = mean(interest_responseNum))

ggplot(EFAanalysis, aes(x = interest_responseNum, color = MWer)) +
  geom_histogram(binwidth = 1, fill = "skyblue", color = "black", alpha = 0.7) +
  labs(title = "Histogram of Interest Response", x = "Value", y = "Frequency") +
  theme_minimal()

ggplot(EFAanalysis, aes(x = interest_responseNum, color = MWer)) +
  geom_density()

Interestwide_data <- EFAanalysis %>%
  group_by(new_exp_column, MWer) %>%
  summarise(mean_value = mean(interest_responseNum),
            sd_value = sd(interest_responseNum)) %>%
  pivot_wider(names_from = MWer, values_from = c(mean_value, sd_value),
              names_glue = "{.value}_{MWer}")

Interestlong_data <- EFAanalysis %>%
  group_by(new_exp_column, MWer) %>%
  summarise(
    N = length(MWer),
    mean_value = mean(interest_responseNum),
    sd_value = sd(interest_responseNum, na.rm = TRUE),
    se_value = sd_value/sqrt(N),
    ciMult = qt(0.95/2 + .5, N-1),
    ci = se_value*ciMult
  )

ggplot(Interestlong_data, aes(x = new_exp_column, y = mean_value, fill = MWer)) +
  geom_bar(stat = "summary", fun = "mean", position = "dodge") +
  scale_fill_manual(values = c("Yes" = "blue", "No" = "red")) +
  geom_errorbar(aes(ymin = mean_value - ci, ymax = mean_value + ci),
                position = position_dodge(1), width = 0.2) +
  labs(title = "Interest Response Scores", x = "Experimental Condition", y = "Average Response Ratings", fill = "Mind Wanderer") +
  scale_x_discrete(labels = c("EXP1" = "Interrupting Probe",
                              "EXP2" = "Post Probe",
                              "EXP3-SART" = "SART",
                              "EXP3-TS" = "Letter/Number Task Switch"))



#GTQ Analysis
MWerByGTQ <- EFAanalysis %>%
  group_by(MWer, new_exp_column, new_cond_column) %>%
  summarise(
    avg_GTQ = mean(GTQ_response))

ggplot(EFAanalysis, aes(x = GTQ_response, color = MWer)) +
  geom_density()

ggplot(EFAanalysis, aes(x = GTQ_response)) +
  geom_histogram(binwidth = 5, fill = "skyblue", color = "black", alpha = 0.7) +
  labs(title = "Histogram of GTQ", x = "Value", y = "Frequency") +
  theme_minimal()

GTQwide_data <- EFAanalysis %>%
  group_by(new_exp_column, MWer) %>%
  summarise(mean_value = mean(GTQ_response),
            sd_value = sd(GTQ_response)) %>%
  pivot_wider(names_from = MWer, values_from = c(mean_value, sd_value),
              names_glue = "{.value}_{MWer}")

GTQlong_data <- EFAanalysis %>%
  group_by(new_exp_column, MWer) %>%
  summarise(
    N = length(MWer),
    mean_value = mean(GTQ_response),
    sd_value = sd(GTQ_response, na.rm = TRUE),
    se_value = sd_value/sqrt(N),
    ciMult = qt(0.95/2 + .5, N-1),
    ci = se_value*ciMult
  )

ggplot(GTQlong_data, aes(x = new_exp_column, y = mean_value, fill = MWer)) +
  geom_bar(stat = "identity", position = "dodge") +
  geom_errorbar(aes(ymin = mean_value - ci, ymax = mean_value + ci),
                position = position_dodge(1), width = 0.2) +
  labs(title = "GTQ Response Scores", x = "Experimental Condition", y = "Mean GTQ Response", fill = "Mind Wanderer") +
  scale_x_discrete(labels = c("EXP1" = "Interrupting Probe",
                              "EXP2" = "Post Probe",
                              "EXP3-SART" = "SART",
                              "EXP3-TS" = "Letter/Number Task Switch"))
  
summary(lm(GTQ_response ~ MWer*new_exp_column, data = EFAanalysis))
summary(lm(GTQ_response ~ MWer*new_exp_column*MR1*MR5, data = EFAanalysis))
summary(lm(GTQ_response ~ MWer+new_exp_column+MR1+MR5, data = EFAanalysis))

ggplot(EFAanalysis, aes(x = MR1, color = MWer)) +
  geom_density()

# ggplot(EFAanalysis, aes(x = MR3, color = Probe)) +
#   geom_density()

Misery <- ggplot(EFAanalysis, aes(x = new_exp_column, y = MR1, fill = MWer)) +
  stat_summary(
    fun = "mean", 
    geom = "bar", 
    position = position_dodge(width = 0.9),
    aes(label = round(..y.., digits = 2)),
    vjust = -0.5
  ) +
  geom_text(
    stat = "summary", 
    fun = "mean", 
    aes(label = round(..y.., digits = 3)),
    position = position_dodge(width = 0.9),
    vjust = -0.5
  ) +
  labs(
   x = "Task Type",
    y = "Average Positive Assessment Ratings",
    title = "Average Positive Assessment Ratings Between Task and Mind Wanderers"
  ) +
  scale_x_discrete(labels = c("EXP1" = "Interrupting Probe",
                              "EXP2" = "Post Probe",
                              "EXP3-SART" = "SART",
                              "EXP3-TS" = "Letter/Number Task Switch")) +
  theme_minimal()
Misery

Misery2 <- ggplot(EFAanalysis, aes(x = MWer, y = MR1, fill = MWer)) +
  stat_summary(
    fun = "mean", 
    geom = "bar", 
    position = position_dodge(width = 0.9),
    aes(label = round(..y.., digits = 2)),
    vjust = -0.5
  ) +
  geom_text(
    stat = "summary", 
    fun = "mean", 
    aes(label = round(..y.., digits = 3)),
    position = position_dodge(width = 0.9),
    vjust = -0.5
  ) +
  labs(
   x = "Task Type",
    y = "Average Factor1 Ratings",
    title = "Average Factor1 Ratings Between Task and Mind Wanderers"
  ) +
  theme_minimal()
Misery2

cor(EFAanalysis$GTQ_response, EFAanalysis$MR1)
cor(EFAanalysis$GTQ_response, EFAanalysis$MR5)

Engaged <- ggplot(EFAanalysis, aes(x = new_exp_column, y = MR5, fill = MWer)) +
  stat_summary(
    fun = "mean", 
    geom = "bar", 
    position = position_dodge(width = 0.9),
    aes(label = round(..y.., digits = 2)),
    vjust = -0.5
  ) +
  geom_text(
    stat = "summary", 
    fun = "mean", 
    aes(label = round(..y.., digits = 3)),
    position = position_dodge(width = 0.9),
    vjust = -0.5
  ) +
  labs(
   x = "Task Type",
    y = "Average Negative Assessment Ratings",
    title = "Average Negative Assessment Ratings Between Task and Mind Wanderers"
  ) +
  scale_x_discrete(labels = c("EXP1" = "Interrupting Probe",
                              "EXP2" = "Post Probe",
                              "EXP3-SART" = "SART",
                              "EXP3-TS" = "Letter/Number Task Switch")) +
  theme_minimal()
Engaged

Engaged2 <- ggplot(EFAanalysis, aes(x = MWer, y = MR5, fill = MWer)) +
  stat_summary(
    fun = "mean", 
    geom = "bar", 
    position = position_dodge(width = 0.9),
    aes(label = round(..y.., digits = 2)),
    vjust = -0.5
  ) +
  geom_text(
    stat = "summary", 
    fun = "mean", 
    aes(label = round(..y.., digits = 3)),
    position = position_dodge(width = 0.9),
    vjust = -0.5
  ) +
  labs(
   x = "Task Type",
    y = "Average Negative Affect Ratings",
    title = "Average Negative Affect Ratings Between Those Who Mind Wanderer and Those \nWho Do Not Mind Wander",
   fill = "Mind Wanderer"  # Change color legend label directly here
  ) +
  theme_minimal()
Engaged2




```



```{r Post Task Analyses for Exp1 and Exp3}
#Use effects coding and center continuous predictors
#Differences in paid response between SONA vs MTurk

print(cor(EFAanalysis[, c('MR1','MR2','MR3', 'MR4', 'MR5')]))

EXP1PostAnalysis <- EFAanalysis %>% filter(new_exp_column != "EXP3-SART")
EXP1PostAnalysis <- EXP1PostAnalysis %>% filter(new_exp_column != "EXP3-TS")

summary(lm(MR1 ~ MWer*new_exp_column, data = EXP1PostAnalysis))
confint(lm(MR1 ~ MWer*new_exp_column, data = EXP1PostAnalysis))
summary(lm(MR5 ~ MWer*new_exp_column, data = EXP1PostAnalysis))

# EXP1PostAnalysis$Probe <- recode(EXP1PostAnalysis$new_exp_column, "'EXP1' = 'IP', 'EXP2' = 'PP', 'EXP3-SART' = 'PP', 'EXP3-TS' = 'PP'", T, F)

EXP1PostAnalysis$Probe <- recode(EXP1PostAnalysis$new_exp_column, 
                                  'EXP1' = 'IP', 
                                  'EXP2' = 'PP', 
                                  'EXP3-SART' = 'PP', 
                                  'EXP3-TS' = 'PP')

# EXP1PostAnalysis$Task <- recode(EXP1PostAnalysis$new_exp_column, "'EXP1' = 'SART'; 'EXP2' = 'SART'; 'EXP3-SART' = 'SART'; 'EXP3-TS' = 'TS'", T, F)

EXP1PostAnalysis$Task <- recode(EXP1PostAnalysis$new_exp_column, 
                                'EXP1' = 'SART', 
                                'EXP2' = 'SART', 
                                'EXP3-SART' = 'SART', 
                                'EXP3-TS' = 'TS')

table(EXP1PostAnalysis$Probe, EXP1PostAnalysis$Task)

# EXP1PostAnalysis$MW <- recode(EXP1PostAnalysis$MWer, "'Yes' = 'MW'; 'No' = 'NMW'", T, F)

EXP1PostAnalysis$MW <- recode(EXP1PostAnalysis$MWer, 
                               'Yes' = 'MW', 
                               'No' = 'NMW')



#Use This Code
PaidMWlmProbeEXP1 <- lm(paid_response~mturk_sona+Probe+new_cond_column+mturk_sona:Probe+mturk_sona:new_cond_column+Probe:new_cond_column, data = EXP1PostAnalysis, contrasts = list(Probe = "contr.sum", new_cond_column = "contr.sum", mturk_sona = "contr.sum"))
summary(PaidMWlmProbeEXP1)
confint(PaidMWlmProbeEXP1)


#Use This Code
PaidMWlmProbeEXP1 <- lm(paid_response~mturk_sona+Probe+MW+mturk_sona:Probe+mturk_sona:MW+Probe:MW, data = EXP1PostAnalysis, contrasts = list(Probe = "contr.sum", MW = "contr.sum", mturk_sona = "contr.sum"))
summary(PaidMWlmProbeEXP1)
confint(PaidMWlmProbeEXP1)
table(EXP1PostAnalysis$Probe, EXP1PostAnalysis$MW)
#

rsq_function <- function(data, indices) {
  d <- data[indices,] #allows boot to select sample
  fit <- lm(paid_response~mturk_sona*Probe*MW, data=d, contrasts = list(Probe = "contr.sum", MW = "contr.sum", mturk_sona = "contr.sum"))
  return(summary(fit)$r.square)
}

boot_model <- lm(paid_response~mturk_sona+Probe+MW+mturk_sona:Probe+mturk_sona:MW+Probe:MW, data = EXP1PostAnalysis, contrasts = list(Probe = "contr.sum", MW = "contr.sum", mturk_sona = "contr.sum"))
reps <- Boot(boot_model, R = 1000)
#reps <- boot(data=EXP1PostAnalysis, statistic=rsq_function, R=1000)
summary(reps)

confint(reps,  level = .95)
plot(reps)

boot.ci(reps, type="bca")

PaidMWlmProbeEXP1 <- lm(paid_response~mturk_sona*new_exp_column*new_cond_column, data = EXP1PostAnalysis, contrasts = list(new_exp_column = "contr.sum", new_cond_column = "contr.sum"))
summary(PaidMWlmProbeEXP1)
confint(PaidMWlmProbeEXP1)

Exp1Paidplot <- ggplot(EXP1PostAnalysis, aes(x = Probe, y = paid_response, fill = Probe)) + 
  geom_violin(trim = FALSE) +
  labs(title = "Average Amount Required to be Paid to Re-enage With the Task by \nProbe Condition", 
       x = "Probe Condition", 
       y = "Average Amount of Payment Required to Re-engage",
       fill = "Probe Condition") +
  scale_x_discrete(labels = c("IP" = "Interrupting Probe", "PP" = "Post Probe")) +
  scale_fill_manual(values = c("IP" = "blue", "PP" = "red"),
                    labels = c("IP" = "Interrupting Probe", "PP" = "Post Probe"))

Exp1Paidplot + stat_summary(fun.data="mean_sdl", mult=1,
                             geom="crossbar", width=0.2, stackdir='center',
                             position=position_dodge(.9))
Exp1Paidplot + stat_summary(fun.data=mean_sdl, mult=1,
                             geom="pointrange", color="black", stackdir='center',
                             position=position_dodge(.9))

PaidMWlmProbeEXP1_data <- EXP1PostAnalysis %>%
  group_by(new_exp_column) %>%
  summarise(
    N = length(subject),
    mean_value = mean(paid_response),
    sd_value = sd(paid_response, na.rm = TRUE),
    se_value = sd_value/sqrt(N),
    ciMult = qt(0.95/2 + .5, N-1),
    ci = se_value*ciMult
  )

#With the legend
# ggplot(PaidMWlmProbeEXP1_data, aes(x = new_exp_column, y = mean_value, fill = new_exp_column)) +
#   geom_bar(stat = "summary", fun = "mean", position = "dodge") +
#   scale_fill_manual(values = c("blue", "red"), 
#                     labels = c("Interrupting Probe", "Post Probe"),
#                     name = "Probe Condition") +
#   geom_errorbar(aes(ymin = mean_value - ci, ymax = mean_value + ci),
#                 position = position_dodge(1), width = 0.2) +
#   labs(title = "Average Reported Amount to be Paid to Re-engage With the Task by Probe Condition",
#        x = "Probe Condition",
#        y = "Average Reported Amount to be Paid") +
#   scale_x_discrete(labels = c("EXP1" = "Interrupting Probe",
#                               "EXP2" = "Post Probe"
#   ))

#With the legend removed
ggplot(PaidMWlmProbeEXP1_data, aes(x = new_exp_column, y = mean_value)) +
  geom_bar(stat = "summary", aes(fill = new_exp_column), fun = "mean", position = "dodge") +
  geom_errorbar(aes(ymin = mean_value - ci, ymax = mean_value + ci),
                position = position_dodge(1), width = 0.2) +
  labs(title = "Average Reported Amount to be Paid to Re-engage With the Task by Probe Condition",
       x = "Probe Condition",
       y = "Average Reported Amount to be Paid") +
  scale_x_discrete(labels = c("EXP1" = "Interrupting Probe",
                              "EXP2" = "Post Probe"
  )) +
  theme(legend.position = "none")

PaidMWlmProbeEXP1_2 <- lm(paid_response~Probe*MW, data = EXP1PostAnalysis, contrasts = list(Probe = "contr.sum", MW = "contr.sum"))
summary(PaidMWlmProbeEXP1_2)
confint(PaidMWlmProbeEXP1_2)
PaidMWlmProbeEXP1_2_data <- EXP1PostAnalysis %>%
  group_by(Probe, MW) %>%
  summarise(
    N = length(subject),
    mean_value = mean(paid_response),
    sd_value = sd(paid_response, na.rm = TRUE),
    se_value = sd_value/sqrt(N),
    ciMult = qt(0.95/2 + .5, N-1),
    ci = se_value*ciMult
  )

ggplot(PaidMWlmProbeEXP1_2_data, aes(x = Probe, y = mean_value, fill = MW)) +
  geom_bar(stat = "summary", fun = "mean", position = "dodge") +
  scale_fill_manual(values = c("MW" = "blue", "NMW" = "red")) +
  geom_errorbar(aes(ymin = mean_value - ci, ymax = mean_value + ci),
                position = position_dodge(1), width = 0.2) +
  labs(title = "Average Reported Amount to be Paid to Re-engage With the Task by Probe Condition\nand Mind Wanderer", x = "Probe Condition", y = "Average Reported Amount to be Paid", fill = "Mind Wanderer") +
  scale_x_discrete(labels = c("IP" = "Interrupting Probe",
                              "PP" = "Post Probe"))

Exp1Paidplot1 <- ggplot(EXP1PostAnalysis, aes(x = Probe, y = paid_response, fill = MW)) + 
  geom_violin(trim = FALSE) +
  labs(title = "Average Amount Required to be Paid to Re-enaged With the Task by \nProbe Condition and Mind Wanderer", 
       x = "Probe Condition", 
       y = "Average Amount of Payment Required to Re-engage",
       fill = "Mind Wanderer") +
  scale_x_discrete(labels = c("IP" = "Interrupting Probe", "PP" = "Post Probe")) +
  scale_fill_manual(values = c("MW" = "blue", "NMW" = "red"),
                    labels = c("MW" = "Mind Wanderer", "NMW" = "Not Mind Wanderer"))

Exp1Paidplot1 + stat_summary(fun.data="mean_sdl", mult=1,
                             geom="crossbar", width=0.2, stackdir='center',
                             position=position_dodge(.9))
Exp1Paidplot1 + stat_summary(fun.data=mean_sdl, mult=1,
                             geom="pointrange", color="black", stackdir='center',
                             position=position_dodge(.9))

PaidLmresult <- EXP1PostAnalysis %>%
  group_by(new_exp_column, MWer) %>%
  summarize(mean_value = mean(paid_response))

# Print the result
print(PaidLmresult)

#
table(EFAanalysis$new_exp_column, EFAanalysis$new_cond_column)


#Do our factors from the EFA, along with mind wandering, affect willingness to reengage?
summary(lm(paid_response ~ new_exp_column*MWer*MR1*MR5, data = EXP1PostAnalysis))




EXP3PostAnalysis <- EFAanalysis %>% filter(new_exp_column != "EXP1")
EXP3PostAnalysis <- EXP3PostAnalysis %>% filter(new_exp_column != "EXP2")


EXP3PostAnalysis$Probe <- recode(EXP3PostAnalysis$new_exp_column,'EXP3-SART' = 'PP', 'EXP3-TS' = 'PP')
EXP3PostAnalysis$Task <- recode(EXP3PostAnalysis$new_exp_column, 'EXP3-SART' = 'SART', 'EXP3-TS' = 'TS')
table(EXP3PostAnalysis$Probe, EXP3PostAnalysis$Task)

EXP3PostAnalysis$MW <- recode(EXP3PostAnalysis$MWer, 'Yes' = 'MW', 'No' = 'NMW')





EXP3PostAnalysis$MWer <- as.factor(EXP3PostAnalysis$MWer)
EXP3PostAnalysis$new_exp_column <- as.factor(EXP3PostAnalysis$new_exp_column)
EXP3PostAnalysis$new_cond_column <- as.factor(EXP3PostAnalysis$new_cond_column)
contrasts(EXP3PostAnalysis$MWer) = contr.sum(2)
contrasts(EXP3PostAnalysis$new_exp_column) = contr.sum(2)
contrasts(EXP3PostAnalysis$new_cond_column) = contr.sum(2)

# summary(lm(paid_response ~ new_exp_column*MWer*scale(MR1,scale = F)*scale(MR5,scale = F), data = EXP3PostAnalysis))
# summary(lm(paid_response ~ new_exp_column+MWer+scale(MR1,scale = F)+scale(MR5,scale = F), data = EXP3PostAnalysis))


PaidMWlmProbeEXP3 <- lm(paid_response~mturk_sona+MW+Task+mturk_sona:Task, data = EXP3PostAnalysis, contrasts = list(mturk_sona = "contr.sum", Task = "contr.sum", MW = "contr.sum"))
summary(PaidMWlmProbeEXP3)
confint(PaidMWlmProbeEXP3)

PaidMWlmProbeEXP3 <- lm(paid_response~MWer+new_exp_column, data = EXP3PostAnalysis, contrasts = list(new_exp_column = "contr.sum", MWer = "contr.sum"))
summary(PaidMWlmProbeEXP3)
confint(PaidMWlmProbeEXP3)

set.seed(123)
library(boot)

rsq_function <- function(formula, data, indices) {
  d <- data[indices,] #allows boot to select sample
  fit <- lm(formula, data=d)
  return(summary(fit)$r.square)
}

boot_model <- lm(paid_response~new_exp_column+MWer, data = EXP3PostAnalysis, contrasts = list(new_exp_column = "contr.sum", MWer = "contr.sum"))
reps <- Boot(boot_model, R = 1000)
#reps <- boot(data=EXP3PostAnalysis, statistic=rsq_function, R=10000, formula=paid_response~new_exp_column+MWer)
summary(reps)

confint(reps,  level = .95)
plot(reps)

boot.ci(reps, type="bca")


Exp3Paidplot <- ggplot(EXP3PostAnalysis, aes(x = Task, y = paid_response, fill = Task)) + 
  geom_violin(trim = FALSE) +
  labs(title = "Average Amount Required to be Paid to Re-enage by Experimental Task", 
       x = "Experimental Task", 
       y = "Average Amount of Payment Required to Re-engage",
       fill = "Experimental Task") +
  scale_x_discrete(labels = c("SART" = "SART", "TS" = "Task Switching")) +
  scale_fill_manual(values = c("SART" = "blue", "TS" = "red"),
                    labels = c("SART" = "SART", "TS" = "Task Switching"))

Exp3Paidplot + stat_summary(fun.data="mean_sdl", mult=1,
                             geom="crossbar", width=0.2, stackdir='center',
                             position=position_dodge(.9))
Exp3Paidplot + stat_summary(fun.data=mean_sdl, mult=1,
                             geom="pointrange", color="black", stackdir='center',
                             position=position_dodge(.9))

PaidMWlmProbeEXP2_data <- EXP3PostAnalysis %>%
  group_by(new_exp_column) %>%
  summarise(
    N = length(subject),
    mean_value = mean(paid_response),
    sd_value = sd(paid_response, na.rm = TRUE),
    se_value = sd_value/sqrt(N),
    ciMult = qt(0.95/2 + .5, N-1),
    ci = se_value*ciMult
  )




#With the legend removed
ggplot(PaidMWlmProbeEXP2_data, aes(x = new_exp_column, y = mean_value)) +
  geom_bar(stat = "summary", aes(fill = new_exp_column), fun = "mean", position = "dodge") +
  geom_errorbar(aes(ymin = mean_value - ci, ymax = mean_value + ci),
                position = position_dodge(1), width = 0.2) +
  labs(title = "Average Reported Amount to be Paid to Re-engage With the Task by Experimental Condition",
       x = "Experimental Task",
       y = "Average Reported Amount to be Paid") +
  scale_x_discrete(labels = c("EXP3-SART" = "SART Task",
                              "EXP3-TS" = "Task Switching Paradigm"
  )) +
  theme(legend.position = "none")


PaidMWlmProbeEXP2_2_data <- EXP3PostAnalysis %>%
  group_by(Probe, MW) %>%
  summarise(
    N = length(subject),
    mean_value = mean(paid_response),
    sd_value = sd(paid_response, na.rm = TRUE),
    se_value = sd_value/sqrt(N),
    ciMult = qt(0.95/2 + .5, N-1),
    ci = se_value*ciMult
  )

#With the legend
 ggplot(PaidMWlmProbeEXP2_2_data, aes(x = Probe, y = mean_value, fill = MW)) +
   geom_bar(stat = "summary", fun = "mean", position = "dodge") +
   scale_fill_manual(values = c("blue", "red"), 
                     labels = c("No", "Yes"),
                     name = "Probe Condition") +
   geom_errorbar(aes(ymin = mean_value - ci, ymax = mean_value + ci),
                 position = position_dodge(1), width = 0.2) +
   labs(title = "Average Reported Amount to be Paid to Re-engage With the Task by Experimental\nCondition and Mind Wanderer",
        x = "Probe Condition",
        y = "Average Reported Amount to be Paid") +
   scale_x_discrete(labels = c("EXP3-SART" = "SART Task",
                              "EXP3-TS" = "Task Switching Paradigm"
   ))

PaidLmresultExp3 <- EXP3PostAnalysis %>%
  group_by(new_exp_column) %>%
  summarize(mean_value = mean(paid_response))

# Print the result
print(PaidLmresult)

EFAanalysisnorm <- EFAanalysis
EFAanalysisnorm$MWer <- as.factor(EFAanalysisnorm$MWer)
EFAanalysisnorm$new_exp_column <- as.factor(EFAanalysisnorm$new_exp_column)
EFAanalysisnorm$new_cond_column <- as.factor(EFAanalysisnorm$new_cond_column)
contrasts(EFAanalysisnorm$MWer) = contr.sum(2)
contrasts(EFAanalysisnorm$new_exp_column) = contr.sum(4)
contrasts(EFAanalysisnorm$new_cond_column) = contr.sum(2)

# #summary(lm(paid_response ~ new_exp_column*MWer*scale(MR1,scale = F)*scale(MR5,scale = F), data = EFAanalysisnorm))
# summary(lm(paid_response~new_exp_column*MWer*scale(MR1,scale = F)*scale(MR5,scale = F), data = EFAanalysis, contrasts = list(new_exp_column = "contr.sum", MWer = "contr.sum")))
# #summary(lm(paid_response ~ new_exp_column+MWer+scale(MR1,scale = F)+scale(MR5,scale = F), data = EFAanalysisnorm))
# summary(lm(paid_response~new_exp_column+MWer+scale(MR1,scale = F)+scale(MR5,scale = F), data = EFAanalysis, contrasts = list(new_exp_column = "contr.sum", MWer = "contr.sum")))
# #summary(lm(MR1 ~ new_exp_column*MWer, data = EFAanalysisnorm))

EFAanalysis$Probe <- recode(EFAanalysis$new_exp_column, 'EXP1' = 'IP', 'EXP2' = 'PP', 'EXP3-SART' = 'PP', 'EXP3-TS' = 'PP')
EFAanalysis$Task <- recode(EFAanalysis$new_exp_column, 'EXP1' = 'SART', 'EXP2' = 'SART', 'EXP3-SART' = 'SART', 'EXP3-TS' = 'TS')
table(EFAanalysis$Probe, EFAanalysis$Task)

EFAanalysis$MW <- recode(EFAanalysis$MWer, 'Yes' = 'MW', 'No' = 'NMW')

#report this model - relevel the MWer factor so Yes is first
Foo <- lm(MR1~Probe+Task+MW+Probe:MW, data = EFAanalysis, contrasts = list(Probe = "contr.sum", Task = "contr.sum", MW = "contr.sum"))
confint(Foo)
summary(Foo)

MR1MWlmProbeEFAanalysis_data <- EFAanalysis %>%
  group_by(Probe, MW) %>%
  summarise(
    N = length(subject),
    mean_value = mean(MR1),
    sd_value = sd(MR1, na.rm = TRUE),
    se_value = sd_value/sqrt(N),
    ciMult = qt(0.95/2 + .5, N-1),
    ci = se_value*ciMult
  )

ggplot(MR1MWlmProbeEFAanalysis_data, aes(x = Probe, y = mean_value, fill = MW)) +
  geom_bar(stat = "summary", fun = "mean", position = "dodge") +
  scale_fill_manual(values = c("MW" = "blue", "NMW" = "red"),
                    labels = c("MW" = "Mind Wanderer", "NMW" = "Not Mind Wanderer")) +
  geom_errorbar(aes(ymin = mean_value - ci, ymax = mean_value + ci),
                position = position_dodge(1), width = 0.2) +
  labs(title = "Average Positive Affect Factor Scores by Probe Condition and Mind Wanderer", x = "Probe Condition", y = "Average Positive Affect Factor Scores", fill = "Mind Wanderer") +
  scale_x_discrete(labels = c("IP" = "Interrupting Probe",
                              "PP" = "Post Probe"))


average_posAffect <- aggregate(MR1 ~ Probe, data = EFAanalysis, FUN = mean_sd)
average_posAffectMW <- aggregate(MR1 ~ MW, data = EFAanalysis, FUN = mean_sd)

MR1plot <- ggplot(EFAanalysis, aes(x = MW, y = MR1, fill = MW)) + 
  geom_violin(trim = FALSE) +
  labs(title = "Average Positive Affect Factor Scores by Mind Wanderer", 
       x = "Mind Wanderer", 
       y = "Average Positive Affect Factor Scores",
       fill = "Mind Wanderer") +
  scale_x_discrete(labels = c("MW" = "Mind Wanderer", "NMW" = "Not Mind Wanderer")) +
  scale_fill_manual(values = c("MW" = "blue", "NMW" = "red"),
                    labels = c("MW" = "Mind Wanderer", "NMW" = "Not Mind Wanderer"))

MR1plot + stat_summary(fun.data="mean_sdl", mult=1, 
                 geom="crossbar", width=0.2 )
MR1plot + stat_summary(fun.data=mean_sdl, mult=1, 
                 geom="pointrange", color="black")

MR1plot_2 <- ggplot(EFAanalysis, aes(x = Probe, y = MR1, fill = Probe)) + 
  geom_violin(trim = FALSE) +
  labs(title = "Average Positive Affect Factor Scores by Probe Condition", 
       x = "Probe", 
       y = "Average Positive Affect Factor Scores",
       fill = "Probe Condition") +
  scale_x_discrete(labels = c("IP" = "Interrupting Probe", "PP" = "Post Probe")) +
  scale_fill_manual(values = c("IP" = "blue", "PP" = "red"),
                    labels = c("IP" = "Interrupting Probe", "PP" = "Post Probe"))

MR1plot_2 + stat_summary(fun.data="mean_sdl", mult=1, 
                 geom="crossbar", width=0.2 )
MR1plot_2 + stat_summary(fun.data=mean_sdl, mult=1, 
                 geom="pointrange", color="black")

Foo <- lm(MR2~Probe+Task+MW+Probe:MW, data = EFAanalysis, contrasts = list(Probe = "contr.sum", Task = "contr.sum", MW = "contr.sum"))
confint(Foo)
summary(Foo)

#Violin Plots
MR2plot <- ggplot(EFAanalysis, aes(x = MW, y = MR2, fill = MW)) + 
  geom_violin(trim = FALSE) +
  labs(title = "Average Stress Factor Scores by Mind Wanderer", 
       x = "Mind Wanderer", 
       y = "Average Stress Factor Scores",
       fill = "Mind Wanderer") +
  scale_x_discrete(labels = c("MW" = "Mind Wanderer", "NMW" = "Not Mind Wanderer")) +
  scale_fill_manual(values = c("MW" = "blue", "NMW" = "red"),
                    labels = c("MW" = "Mind Wanderer", "NMW" = "Not Mind Wanderer"))

MR2plot + stat_summary(fun.data="mean_sdl", mult=1, 
                 geom="crossbar", width=0.2 )
MR2plot + stat_summary(fun.data=mean_sdl, mult=1, 
                 geom="pointrange", color="black")

Foo <- lm(MR3~Probe+Task+MW+Probe:MW, data = EFAanalysis, contrasts = list(Probe = "contr.sum", Task = "contr.sum", MW = "contr.sum"))
confint(Foo)
summary(Foo)

average_GTQprobe <- aggregate(MR3 ~ Probe, data = EFAanalysis, FUN = mean_sd)

MR3MWlmProbeEFAanalysis_data <- EFAanalysis %>%
  group_by(Probe) %>%
  summarise(
    N = length(subject),
    mean_value = mean(MR1),
    sd_value = sd(MR1, na.rm = TRUE),
    se_value = sd_value/sqrt(N),
    ciMult = qt(0.95/2 + .5, N-1),
    ci = se_value*ciMult
  )

ggplot(MR3MWlmProbeEFAanalysis_data, aes(x = Probe, y = mean_value, fill = Probe)) +
  geom_bar(stat = "summary", fun = "mean", position = "dodge") +
  scale_fill_manual(values = c("IP" = "blue", "PP" = "red"),
                    labels = c("IP" = "Interrupting Probe", "PP" = "Post Probe")) +
  geom_errorbar(aes(ymin = mean_value - ci, ymax = mean_value + ci),
                position = position_dodge(1), width = 0.2) +
  labs(title = "Average GTQ Scores by Probe Condition", x = "Probe Condition", y = "Average GTQ Scores", fill = "Probe Condition") +
  scale_x_discrete(labels = c("IP" = "Interrupting Probe",
                              "PP" = "Post Probe"))

#Violin Plots
MR3plot <- ggplot(EFAanalysis, aes(x = Probe, y = MR3, fill = Probe)) + 
  geom_violin(trim = FALSE) +
  labs(title = "Average GTQ Factor Scores by Probe Condition", 
       x = "Probe", 
       y = "Average GTQ Factor Scores",
       fill = "Probe Condition") +
  scale_x_discrete(labels = c("IP" = "Interrupting Probe", "PP" = "Post Probe")) +
  scale_fill_manual(values = c("IP" = "blue", "PP" = "red"),
                    labels = c("IP" = "Interrupting Probe", "PP" = "Post Probe"))

MR3plot + stat_summary(fun.data="mean_sdl", mult=1, 
                 geom="crossbar", width=0.2 )
MR3plot + stat_summary(fun.data=mean_sdl, mult=1, 
                 geom="pointrange", color="black")

Foo <- lm(MR4~Probe+Task+MW+Probe:MW, data = EFAanalysis, contrasts = list(Probe = "contr.sum", Task = "contr.sum", MW = "contr.sum"))
confint(Foo)
summary(Foo)


Foo <- lm(MR5~Probe+Task+MW+Probe:MW, data = EFAanalysis, contrasts = list(Probe = "contr.sum", Task = "contr.sum", MW = "contr.sum"))
summary(Foo)
confint(Foo)

average_stressMW <- aggregate(MR5 ~ MW, data = EFAanalysis, FUN = mean_sd)

MR5plot <- ggplot(EFAanalysis, aes(x = MW, y = MR5, fill = MW)) + 
  geom_violin(trim = FALSE) +
  labs(title = "Average Stress Factor Scores by Mind Wanderer", 
       x = "Mind Wanderer", 
       y = "Average Stress Factor Scores",
       fill = "Mind Wanderer") +
  scale_x_discrete(labels = c("MW" = "Mind Wanderer", "NMW" = "Not Mind Wanderer")) +
  scale_fill_manual(values = c("MW" = "blue", "NMW" = "red"),
                    labels = c("MW" = "Mind Wanderer", "NMW" = "Not Mind Wanderer"))

MR5plot + stat_summary(fun.data="mean_sdl", mult=1, 
                 geom="crossbar", width=0.2 )
MR5plot + stat_summary(fun.data=mean_sdl, mult=1, 
                 geom="pointrange", color="black")
#dropping mturk_sona - too unbalanced, mturk is disproportionate of PP to IP, is a confound, not orthogonal.  too much of a proxy variable.  But leave in for the paid response models.  The effects are big for probe.

######################################################################################################################Ignore the following
#####################################################################################################################
# Foo <- lm(MR1~mturk_sona+Probe+Task+MW+Probe:MW, data = EFAanalysis, contrasts = list(Probe = "contr.sum", Task = "contr.sum", MW = "contr.sum"))
# summary(Foo)
# confint(Foo)
# 
# 
# 
# 
# Foo <- lm(MR2~mturk_sona+Probe+Task+MW+Probe:MW, data = EFAanalysis, contrasts = list(Probe = "contr.sum", Task = "contr.sum", MW = "contr.sum"))
# 
# summary(Foo)
# 
# Foo <- lm(MR3~mturk_sona+Probe+Task+MW+Probe:MW, data = EFAanalysis, contrasts = list(Probe = "contr.sum", Task = "contr.sum", MW = "contr.sum"))
# confint(Foo)
# summary(Foo)
# 
# 
# 
# Foo <- lm(MR4~mturk_sona+Probe+Task+MW+Probe:MW, data = EFAanalysis, contrasts = list(Probe = "contr.sum", Task = "contr.sum", MW = "contr.sum"))
# 
# summary(Foo)
# 
# 
# Foo <- lm(MR5~mturk_sona+Probe+Task+MW+Probe:MW, data = EFAanalysis, contrasts = list(Probe = "contr.sum", Task = "contr.sum", MW = "contr.sum"))
# summary(Foo)
# 
# table(EFAanalysis$mturk_sona, EFAanalysis$Probe)
# 
# Foo <- lm(MR5~Probe*Task*MW, data = EFAanalysis, contrasts = list(Probe = "contr.sum", Task = "contr.sum", MW = "contr.sum"))
# 
# summary(Foo)
# 
# 
# 
# 
# Foo <- lm(paid_response~Probe+Task+MW+Probe:MW, data = EFAanalysis, contrasts = list(Probe = "contr.sum", Task = "contr.sum", MW = "contr.sum"))
# 
# summary(Foo)
# 
# PaidMWlmProbeEFA_2_data <- EFAanalysis %>%
#   group_by(Probe, MW) %>%
#   summarise(
#     N = length(subject),
#     mean_value = mean(paid_response),
#     sd_value = sd(paid_response, na.rm = TRUE),
#     se_value = sd_value/sqrt(N),
#     ciMult = qt(0.95/2 + .5, N-1),
#     ci = se_value*ciMult
#   )
# 
# ggplot(PaidMWlmProbeEFA_2_data, aes(x = Probe, y = mean_value, fill = MW)) +
#   geom_bar(stat = "summary", fun = "mean", position = "dodge") +
#   scale_fill_manual(values = c("MW" = "blue", "NMW" = "red")) +
#   geom_errorbar(aes(ymin = mean_value - ci, ymax = mean_value + ci),
#                 position = position_dodge(1), width = 0.2) +
#   labs(title = "Average Reported Amount to be Paid to Re-engage With the Task by Probe Condition\nand Mind Wanderer", x = "Probe Condition", y = "Average Reported Amount to be Paid", fill = "Mind Wanderer") +
#   scale_x_discrete(labels = c("IP" = "Interrupting Probe",
#                               "PP" = "Post Probe"))
# 
# 
# 
# Foo <- lm(paid_response~Probe+Task+MW+Probe:MW+Task:MW, data = EFAanalysis, contrasts = list(Probe = "contr.sum", Task = "contr.sum", MW = "contr.sum"))
# 
# summary(Foo)
# 
# Foo <- lm(paid_response~Probe+Task+MW+Probe:MW, data = EFAanalysis, contrasts = list(Probe = "contr.sum", Task = "contr.sum", MW = "contr.sum"))
# 
# summary(Foo)
# 
# Foo <- lm(paid_response~Probe+Task+MW+Task:MW, data = EFAanalysis, contrasts = list(Probe = "contr.sum", Task = "contr.sum", MW = "contr.sum"))
# 
# summary(Foo)
#####################################################################################################################
EFAanalysis$mturk_sona <- as.factor(EFAanalysis$mturk_sona)

#Use this for the report
Foo <- lm(paid_response~Probe+MW+Task+Probe:MW , data = EFAanalysis, contrasts = list(mturk_sona = "contr.sum", Probe = "contr.sum", Task = "contr.sum", MW = "contr.sum"))
summary(Foo)
confint(Foo)


PaidRespS3 <- ggplot(EFAanalysis, aes(x = Probe, y = paid_response, fill = MW)) + 
  geom_violin(trim = FALSE) +
  labs(title = "Average Reported Amount to be Paid to Re-Engage With the Task by Probe Condition \nand Mind Wanderer", 
       x = "Probe Condition", 
       y = "Average Paid Response",
       fill = "Mind Wanderer") +
  scale_x_discrete(labels = c("MW" = "Mind Wanderer", "NMW" = "Not Mind Wanderer")) +
  scale_fill_manual(values = c("MW" = "blue", "NMW" = "red"),
                    labels = c("MW" = "Mind Wanderer", "NMW" = "Not Mind Wanderer")) 

PaidRespS3 + stat_summary(fun.data="mean_sdl", mult=1,
                                  geom="crossbar", width=0.2, stackdir='center',
                                  position=position_dodge(.9))
PaidRespS3 + stat_summary(fun.data=mean_sdl, mult=1,
                                  geom="pointrange", color="black", stackdir='center',
                                  position=position_dodge(.9))


#Changed to exclude from report.  Are not including the mturk_sona predictor.
# Foo <- lm(paid_response~mturk_sona+Probe+MW+Task+Probe:MW , data = EFAanalysis, contrasts = list(mturk_sona = "contr.sum", Probe = "contr.sum", Task = "contr.sum", MW = "contr.sum"))
# summary(Foo)
# confint(Foo)


# Foo <- lm(paid_response~MW, data = EFAanalysis, contrasts = list(Probe = "contr.sum", Task = "contr.sum", MW = "contr.sum"))
# 
# summary(Foo)
# 
# table(EFAanalysis$Probe, EFAanalysis$MW)
# 
# Foo <- lm(MR3~Probe*Task*MW, data = EFAanalysis, contrasts = list(Probe = "contr.sum", Task = "contr.sum", MW = "contr.sum"))
# 
# summary(Foo)
# 
# Foo <- lm(MR3~Probe+Task+MW+Probe:MW, data = EFAanalysis, contrasts = list(Probe = "contr.sum", Task = "contr.sum", MW = "contr.sum"))
# 
# summary(Foo)
# 
# Foo <- lm(MR4~Probe*Task*MW, data = EFAanalysis, contrasts = list(Probe = "contr.sum", Task = "contr.sum", MW = "contr.sum"))
# 
# summary(Foo)
# 
# Foo <- lm(MR2~Probe*Task*MW, data = EFAanalysis, contrasts = list(Probe = "contr.sum", Task = "contr.sum", MW = "contr.sum"))
# 
# summary(Foo)


# summary(lm(MR1~new_exp_column*MWer, data = EFAanalysis, contrasts = list(new_exp_column = "contr.sum", MWer = "contr.sum")))
# confint(lm(MR1~new_exp_column*MWer, data = EFAanalysis, contrasts = list(new_exp_column = "contr.sum", MWer = "contr.sum")))
# #summary(lm(MR1 ~ new_exp_column+MWer, data = EFAanalysisnorm))
# summary(lm(MR1~new_exp_column+MWer, data = EFAanalysis, contrasts = list(new_exp_column = "contr.sum", MWer = "contr.sum")))
# #summary(lm(MR5 ~ new_exp_column*MWer, data = EFAanalysisnorm))
# 
# summary(lm(MR5~new_exp_column*MWer, data = EFAanalysis, contrasts = list(new_exp_column = "contr.sum", MWer = "contr.sum")))
# 
# table(EFAanalysis$Probe, EFAanalysis$MWer)
# table(EFAanalysis$Task, EFAanalysis$MWer)

vif(Foo) #colinearity, multi colinearity not enough to change the effects

# summary(lm(MR5~new_exp_column*MWer, data = EFAanalysis, contrasts = list(new_exp_column = "contr.sum", MWer = "contr.sum")))
# confint(lm(MR5~new_exp_column*MWer, data = EFAanalysis, contrasts = list(new_exp_column = "contr.sum", MWer = "contr.sum")))
# #summary(lm(MR5 ~ new_exp_column+MWer, data = EFAanalysisnorm))
# summary(lm(MR5~new_exp_column+MWer, data = EFAanalysis, contrasts = list(new_exp_column = "contr.sum", MWer = "contr.sum")))
# #summary(lm(paid_response ~ MWer, data = EFAanalysisnorm))
# summary(lm(paid_response~MWer, data = EFAanalysis, contrasts = list(MWer = "contr.sum")))
# confint(lm(paid_response~MWer, data = EFAanalysis, contrasts = list(MWer = "contr.sum")))
# 
# summary(lm(MR1 ~ MWer*new_exp_column, data = EXP3PostAnalysis))
# summary(lm(MR5 ~ MWer*new_exp_column, data = EXP3PostAnalysis))
# summary(lm(paid_response ~ new_exp_column*MWer, data = EXP3PostAnalysis))
# summary(lm(paid_response ~ new_exp_column+MWer, data = EXP3PostAnalysis))
# summary(lm(paid_response ~ new_exp_column*MWer*scale(MR1,scale = F)*scale(MR5,scale = F), data = EXP3PostAnalysis))
# summary(lm(paid_response ~ new_exp_column+MWer+scale(MR1,scale = F)*scale(MR5,scale = F), data = EXP3PostAnalysis))
# 
# summary(lm(paid_response ~ new_exp_column*MWer*MR1*MR5, data = EFAanalysis))
# 
# ggplot(EFAanalysis, aes(x = as.factor(MWer), y = paid_response, group = new_exp_column, color = new_exp_column)) +
#   stat_summary(fun = "mean", geom = "line", aes(group = new_exp_column)) +
#   stat_summary(fun = "mean", geom = "point", aes(group = new_exp_column)) +
#   labs(x = "Mind Wander", y = "Paid Response", color = "Experiment")
# 
# ggplot(EFAanalysis, aes(x = as.factor(new_exp_column), y = paid_response, group = new_exp_column, color = MWer)) +
#   stat_summary(fun = "mean", geom = "line", aes(group = MWer)) +
#   stat_summary(fun = "mean", geom = "point", aes(group = MWer)) +
#   labs(x = "Experiment", y = "Paid Response", color = "Mind Wander")

#=================================================================================================
#Catch Trials - I don't think we can do a proper analysis of the Catch Trials
#=================================================================================================
# EXP1CatchAnalysis <- EXP1PostAnalysis %>% dplyr::select(c("subject", "MWer", "new_exp_column", "new_cond_column"))
# EXP1CatchAnalysis <-EXP1CatchAnalysis %>% filter(new_exp_column == "EXP1")
# EXP1CatchAnalysis <- EXP1CatchAnalysis %>% left_join(EXP1MWcatchTrialsAverages, by = "subject")
# 
# EXP2CatchAnalysis <- EXP1PostAnalysis %>% dplyr::select(c("subject", "MWer", "new_exp_column", "new_cond_column", "MWcatch_response", "MWonTask_response", "MWother_response"))
# EXP2CatchAnalysis <- EXP2CatchAnalysis %>% filter(new_exp_column == "EXP2")
# 
# EXP3CatchAnalysis <- EXP3PostAnalysis %>% dplyr::select(c("subject", "MWer", "new_exp_column", "new_cond_column", "MWcatch_response", "MWonTask_response", "MWother_response"))
# EXP3CatchAnalysis <- EXP3CatchAnalysis %>% filter(new_exp_column != "EXP1")
# EXP3CatchAnalysis <- EXP3CatchAnalysis %>% filter(new_exp_column != "EXP2")
# 
# AllParticipantCatchTrials <- rbind(EXP1CatchAnalysis, EXP2CatchAnalysis, EXP3CatchAnalysis)
# 
# #These are the people who are missing Catch Trial Responses
# NoResponsesForCatchTrials <- aggregate(. ~ new_exp_column + new_cond_column, data = AllParticipantCatchTrials[, c("new_exp_column", "new_cond_column", "MWcatch_response", "MWonTask_response", "MWother_response")], FUN = function(x) sum(is.na(x)), na.action = na.pass)
# 
# TotalParticipantForEachCond <- AllParticipantCatchTrials %>% group_by(new_exp_column) %>% count(new_cond_column)
# 
# NoResponsesForCatchTrials <- NoResponsesForCatchTrials %>% left_join(TotalParticipantForEachCond, by = c("new_exp_column", "new_cond_column"))
# 
# 
# AllParticipantCatchTrialsNAremoved <- AllParticipantCatchTrials[complete.cases(AllParticipantCatchTrials), ]
# 
# MWCatchTrials_data <- AllParticipantCatchTrialsNAremoved %>%
#   group_by(new_exp_column, MWer) %>%
#   summarise(mean_value = mean(MWcatch_response),
#             sd_value = sd(MWcatch_response)) %>%
#   pivot_wider(names_from = MWer, values_from = c(mean_value, sd_value),
#               names_glue = "{.value}_{MWer}")
# 
# MWCatchTrialslong_data <- AllParticipantCatchTrialsNAremoved %>%
#   group_by(new_exp_column, MWer) %>%
#   summarise(
#     N = length(MWer),
#     mean_value = mean(MWcatch_response),
#     sd_value = sd(MWcatch_response, na.rm = TRUE),
#     se_value = sd_value/sqrt(N),
#     ciMult = qt(0.95/2 + .5, N-1),
#     ci = se_value*ciMult
#   )
# 
# ggplot(MWCatchTrialslong_data, aes(x = new_exp_column, y = mean_value, fill = MWer)) +
#   geom_bar(stat = "summary", fun = "mean", position = "dodge") +
#   scale_fill_manual(values = c("Yes" = "blue", "No" = "red")) +
#   geom_errorbar(aes(ymin = mean_value - ci, ymax = mean_value + ci),
#                 position = position_dodge(1), width = 0.2) +
#   labs(title = "Catch Trials Response Scores", x = "Experimental Condition", y = "Average MW Catch TrialsResponse Ratings", fill = "Mind Wanderer") +
#   scale_x_discrete(labels = c("EXP1" = "Interrupting Probe",
#                               "EXP2" = "Post Probe",
#                               "EXP3-SART" = "SART",
#                               "EXP3-TS" = "Letter/Number Task Switch"))
# 
# 
# OnTaskCatchTrials_data <- AllParticipantCatchTrialsNAremoved %>%
#   group_by(new_exp_column, MWer) %>%
#   summarise(mean_value = mean(MWonTask_response),
#             sd_value = sd(MWonTask_response)) %>%
#   pivot_wider(names_from = MWer, values_from = c(mean_value, sd_value),
#               names_glue = "{.value}_{MWer}")
# 
# OnTaskCatchTrialslong_data <- AllParticipantCatchTrialsNAremoved %>%
#   group_by(new_exp_column, MWer) %>%
#   summarise(
#     N = length(MWer),
#     mean_value = mean(MWonTask_response),
#     sd_value = sd(MWonTask_response, na.rm = TRUE),
#     se_value = sd_value/sqrt(N),
#     ciMult = qt(0.95/2 + .5, N-1),
#     ci = se_value*ciMult
#   )
# 
# ggplot(OnTaskCatchTrialslong_data, aes(x = new_exp_column, y = mean_value, fill = MWer)) +
#   geom_bar(stat = "summary", fun = "mean", position = "dodge") +
#   scale_fill_manual(values = c("Yes" = "blue", "No" = "red")) +
#   geom_errorbar(aes(ymin = mean_value - ci, ymax = mean_value + ci),
#                 position = position_dodge(1), width = 0.2) +
#   labs(title = "Catch Trials Response Scores", x = "Experimental Condition", y = "Average On Task Catch TrialsResponse Ratings", fill = "Mind Wanderer") +
#   scale_x_discrete(labels = c("EXP1" = "Interrupting Probe",
#                               "EXP2" = "Post Probe",
#                               "EXP3-SART" = "SART",
#                               "EXP3-TS" = "Letter/Number Task Switch"))
# 
# 
# OtherCatchTrials_data <- AllParticipantCatchTrialsNAremoved %>%
#   group_by(new_exp_column, MWer) %>%
#   summarise(mean_value = mean(MWother_response),
#             sd_value = sd(MWother_response)) %>%
#   pivot_wider(names_from = MWer, values_from = c(mean_value, sd_value),
#               names_glue = "{.value}_{MWer}")
# 
# OtherCatchTrialslong_data <- AllParticipantCatchTrialsNAremoved %>%
#   group_by(new_exp_column, MWer) %>%
#   summarise(
#     N = length(MWer),
#     mean_value = mean(MWother_response),
#     sd_value = sd(MWother_response, na.rm = TRUE),
#     se_value = sd_value/sqrt(N),
#     ciMult = qt(0.95/2 + .5, N-1),
#     ci = se_value*ciMult
#   )
# 
# ggplot(OtherCatchTrialslong_data, aes(x = new_exp_column, y = mean_value, fill = MWer)) +
#   geom_bar(stat = "summary", fun = "mean", position = "dodge") +
#   scale_fill_manual(values = c("Yes" = "blue", "No" = "red")) +
#   geom_errorbar(aes(ymin = mean_value - ci, ymax = mean_value + ci),
#                 position = position_dodge(1), width = 0.2) +
#   labs(title = "Catch Trials Response Scores", x = "Experimental Condition", y = "Average Other Catch TrialsResponse Ratings", fill = "Mind Wanderer") +
#   scale_x_discrete(labels = c("EXP1" = "Interrupting Probe",
#                               "EXP2" = "Post Probe",
#                               "EXP3-SART" = "SART",
#                               "EXP3-TS" = "Letter/Number Task Switch"))
# 
# 
# summary(lm(MWcatch_response ~ new_exp_column*new_cond_column, data = AllParticipantCatchTrialsNAremoved))
# summary(lm(MWcatch_response ~ new_exp_column, data = AllParticipantCatchTrialsNAremoved))
# summary(lm(MWcatch_response ~ new_cond_column, data = AllParticipantCatchTrialsNAremoved))
# summary(lm(MWonTask_response ~ new_exp_column*new_cond_column, data = AllParticipantCatchTrialsNAremoved))
# summary(lm(MWonTask_response ~ new_exp_column, data = AllParticipantCatchTrialsNAremoved))
# summary(lm(MWonTask_response ~ new_cond_column, data = AllParticipantCatchTrialsNAremoved))
# summary(lm(MWother_response ~ new_exp_column*new_cond_column, data = AllParticipantCatchTrialsNAremoved))
# summary(lm(MWother_response ~ new_exp_column, data = AllParticipantCatchTrialsNAremoved))
# summary(lm(MWother_response ~ new_cond_column, data = AllParticipantCatchTrialsNAremoved))
# 
# 
# EFAanalysisnorm %>% group_by(new_exp_column) %>% count(mturk_sona)
# 
# tapply(EFAanalysisnorm$paid_response, EFAanalysisnorm$mturk_sona, mean)
# 
# aggregate(EFAanalysisnorm$paid_response, 
#                                    by = list(EFAanalysisnorm$new_exp_column, EFAanalysisnorm$mturk_sona), 
#                                    FUN = mean)

```

